action: call-service
service: honeycomb
service_data:
  audio: /local/sound/popup.m4a
  autoclose: true
  buttons:
    #0
    - icon: phu:ceiling-adore-flush
      position: 0
      show: true
      entity: light.utility_room_light
      active: '[[[ return entity.state != "off" ]]]'
      tap_action:
        action: call-service
        service: light.toggle
        service_data:
          entity_id: entity
    #1
    - icon: phu:roborock
      position: 1
      show: true
      entity: vacuum.roidmi_eve
      active: '[[[ return entity.state != "docked" ]]]'
      tap_action: !include ../popup/footer/footer_vacuum.yaml

    #2
    - icon: mdi:play-pause
      position: 2
      show: true
      entity: vacuum.roidmi_eve
      tap_action:
        action: call-service
        service: >
          [[[
            return `[[[
              return entity.state === 'docked' || entity.state === 'paused'
                ? 'vacuum.start'
                : 'vacuum.pause';
            ]]]`
          ]]]
        service_data:
          entity_id: vacuum.roidmi_eve
    #3
    - icon: mdi:battery-charging
      position: 3
      show: true
      entity: vacuum.roidmi_eve
      active: '[[[ return entity.state != "docked" ]]]'
      tap_action:
        action: call-service
        service: vacuum.return_to_base
        service_data:
          entity_id: vacuum.roidmi_eve
    #4
    - icon: mdi:delete-empty
      position: 4
      show: true
      entity: vacuum.roidmi_eve
      active: '[[[ return entity.state != "docked" ]]]'
      tap_action:
        action: call-service
        service: script.vacuum_empty_bin
