action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Playstation
    card_mod:
      style:
        #popup header
        .:
    content:
      type: entities
      state_color: true
      card_mod:
        class: content
      entities:

        - entity: switch.ps5_635_power
          name: Playstation 5
          secondary_info: last-changed
