action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Zuzu
    style: >
      --popup-max-width: calc(450px + 450px);
    card_mod:
      style:
        .: |

        layout-card:
          $grid-layout$:
            # card divider border
            .: |
              #root > * {
                margin: 0px !important;
              }
              @media (max-width: 450px), (max-height: 500px) {
                #root {
                  display: block !important;
                }
              }
            hui-vertical-stack-card$: |
              #root {
                border-right: 0.1vw solid rgba(58, 69, 73, 0.2);
                border-radius: 0;
                transition: none;
              }
              /* portrait */
              @media screen and (max-width: 800px) {
                #root{
                  border-right: none;
                  border-bottom: 0.1vw solid rgba(58, 69, 73, 0.2);
                }
              }

    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 450px 450px
        grid-template-areas: |
          "person history"
        mediaquery:
          #portrait
          '(max-width: 1200px)':
            grid-template-columns: 1fr
            grid-template-rows: fit-content(100%)
            grid-template-areas: |
              "person"
              "history"
      cards:
        #################################################
        #                                               #
        #                PERSON POPUP                   #
        #                                               #
        #################################################
        - type: vertical-stack
          view_layout:
            grid-area: person
          cards:
            - type: entities
              card_mod:
                class: content
              entities:
                - entity: person.huong_giang
                  secondary_info: last-changed
                - type: attribute
                  entity: sensor.gle
                  attribute: 'Formatted Address'
                  icon: mdi:car
                  name: GLE
            - type: history-graph
              card_mod:
                style: |
                  ha-card > div {
                    padding: 0 0.5em !important;
                  }
              entities:
                - entity: person.huong_giang
                  name: ' '
            - type: map
              default_zoom: 14
              dark_mode: true
              hours_to_show: 12
              entities:
                - device_tracker.findmy_d098350b38e241d3972ad394a27f38b6
              card_mod:
                style:
                  .: |
                    #root {
                      height: 25em;
                      padding-bottom: 0 !important;
                    }
                    ha-icon-button {
                      color: var(--primary-color);
                      zoom: 140%;
                      margin-left: -0.2em;
                    }
                    ha-card {
                      border-radius: 12px;
                      transition: none;
                      height: 25em !important;
                    }
                  ha-map$: |
                    #map {
                      background-color: #191919 !important;
                    }
                    .leaflet-control-attribution {
                      display: none;
                    }
                    .leaflet-bar a {
                      background-color: rgba(115, 123, 124, 0.2) !important;
                      color: #9da0a2 !important;
                      backdrop-filter: blur(0.25em);
                      zoom: 140%;
                    }
                    a.leaflet-control-zoom-in {
                      border-bottom: 1px solid #181818 !important;
                    }
                    .leaflet-pane.leaflet-tile-pane {
                      filter: invert(0.95) grayscale(0.95) contrast(95%);
                    }
        - type: logbook
          view_layout:
            grid-area: history
          title: Logbook
          entities:
            - sensor.gle
          hours_to_show: 24
          style: |
            ha-card {
              display: block !imporant;
              border: none !important;
              justify-content: unset;
              align-items: stretch;
              margin-inline: 5px;
            }
            ha-logbook {
              height: 470px !important;
            }
            .content {
              padding: 0 !important;
            }
            lit-virtualizer {
              overflow: hidden !important;
            }
            .narrow .entry {
              line-height: unset;
            }
