action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Monitorer
    card_mod:
      style:
        #popup header
        .:
    content:

      type: vertical-stack
      cards:

        - type: entities
          state_color: true
          card_mod:
            class: content
          entities:

            - entity: switch.gosund_monitors_switch
              secondary_info: last-changed

            - type: custom:slider-entity-row
              card_mod:
                style:
                  # icon color mute and max
                  .: |
                    :host {
                      --paper-item-icon-color:
                        {% if is_state('binary_sensor.monitors_mute_state', 'on') %}
                          #FFFFFF20
                        {% elif states(config.entity) | int == 0 %}
                          #9da0a2
                        {% elif states(config.entity) | int < 60 %}
                          initial
                        {% else %}
                          red
                        {% endif %};
                      }
                  # full width slider
                  hui-generic-entity-row$: |
                    div {
                      flex: auto !important;
                    }
              entity: input_number.monitors_volume
              hide_state: false

            - entity: automation.monitors_turn_off

            - entity: automation.monitors_calibration

        - type: custom:mod-card
          card_mod:
            style:
              hui-horizontal-stack-card$: |
                #root {
                  justify-content: space-evenly !important;
                  padding: var(--tablet-popup-button-padding);
                }
          card:

            type: horizontal-stack
            cards:

              - type: custom:button-card
                entity: switch.monitors_mute
                icon: mdi:volume-mute
                tap_action:
                  action: toggle
                template: icon_only

              - type: custom:button-card
                icon: mdi:volume-minus
                tap_action:
                  action: call-service
                  service: input_number.decrement
                  service_data:
                    entity_id: input_number.monitors_volume
                template: icon_only

              - type: custom:button-card
                icon: mdi:volume-plus
                tap_action:
                  action: call-service
                  service: input_number.increment
                  service_data:
                    entity_id: input_number.monitors_volume
                template: icon_only
