action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: SONY TV
    style: >
      --tablet-popup-header-color: rgba(0, 0, 0, 0);
      --popup-background-color: rgba(0, 0, 0, 0);
      --popup-border-width: 0;
      --button-card-border-radius: 10%;
      --grid-card-gap: 5%;
    card_mod:
      style:
        .: |
          ha-header-bar {
            display: none !important;
          }
          @media screen and (max-width: 800px) {
            ha-header-bar {
              display: block !important;
            }
          }

    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        grid-template-columns: 1fr
        grid-template-rows: 1fr
        grid-template-areas: |
          "hallway"
      cards:
        - type: grid
          #title: hallway
          view_layout:
            grid-area: hallway
          columns: 3
          cards:
            - type: custom:button-card
              icon: mdi:home-variant
              entity: media_player.living_room_tv
              template:
                - remote
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.atv
                  command: menu
            - type: custom:button-card
              icon: mdi:home-variant
              entity: media_player.living_room_tv
              template:
                - remote
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.atv
                  command: menu
            - type: custom:button-card
              icon: mdi:home-variant
              entity: media_player.living_room_tv
              template:
                - remote
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.atv
                  command: menu
