action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    size: fullscreen
    style: |
      --popup-border-width: 0;
      --tablet-popup-header-color: rgba(0, 0, 0, 0);
      --popup-background-color: rgba(0, 0, 0, 0);
    card_mod:
      style:
        .: |
          ha-header-bar {
            display: none !important;
          }
    content:
        type: custom:mod-card
        card_mod:
        style: |
          ha-card {
            background: rgba(115, 115, 115, 0.2);
            border-start-start-radius: 1vw;
            border-start-end-radius: 1vw;
            overflow: hidden;
          }
        card:
          type: custom:tabbed-card
          styles: # global styles applied to all tabs
            --mdc-theme-primary: 'rgba(250, 250, 250, 0.75)'
            --mdc-tab-text-label-color-default: '#97989c'

          tabs:
            - card:
                type: iframe
                url: https://ymovie.streamcinema.cz/#/scc/browse/Movies
                aspect_ratio: 100%
              attributes:
                label: Movies
                icon: mdi:movie-open-star
            - card:
                type: iframe
                url: https://ymovie.streamcinema.cz/#/scc/browse/Series
                aspect_ratio: 100%
              attributes:
                label: Series
                icon: mdi:television

            - card:
                type: iframe
                url: https://ymovie.streamcinema.cz/#/scc/browse/Popular-Movies
                aspect_ratio: 100%
              attributes:
                label: Popular
                icon: mdi:star
