action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: System Information
    style: >
      --popup-max-width: calc(455px + 455px + 455px);
    card_mod:
      style:
        .: |

        layout-card$grid-layout$:
          .: |
            #root > * {
              margin: 0px !important;
            }
          hui-entities-card:
            $: |
              ha-card {
                border-right: 0.1vw solid rgba(58, 69, 73, 0.2);
                border-radius: 0;
                transition: none;
              }

              /* portrait */
              @media screen and (max-width: 1400px) {
                ha-card {
                  border-right: none;
                  border-bottom: 0.1vw solid rgba(58, 69, 73, 0.2);
                }
              }
            $hui-horizontal-stack-card:
              # horizontal bottom buttons
              $: |
                #root {
                  justify-content: space-evenly;
                  margin-top: 1.7em;
                }
    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 450px  450px  450px
        grid-template-areas: |
          "hass docker containers"
        mediaquery:
          #portrait
          '(max-width: 1400px)':
            grid-template-columns: 1fr
            grid-template-rows: fit-content(100%)
            grid-template-areas: |
              "hass"
              "docker"
              "containers"
      cards:
        #################################################
        #                                               #
        #                HOME ASSISTANT                 #
        #                                               #
        #################################################
        - type: entities
          view_layout:
            grid-area: hass
          title: Home Assistant
          show_header_toggle: false
          card_mod:
            class: header
          entities:
            - entity: sensor.current_version
              name: Installed
              icon: mdi:home-assistant

            # - entity: sensor.home_assistant_versions
            #   name: Latest

            # - entity: sensor.template_hass_next_release

            - entity: sensor.ha_db
              name: Database
              icon: mdi:database

            # - entity: sensor.home_assistant_log_size
            #   name: Logfile
            #   icon: mdi:file-document

            - type: attribute
              entity: sensor.backup_state
              attribute: last_backup
              name: Last backup
              icon: mdi:cloud-upload
              format: relative

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              # unit_of_measurement: '%'
              positions: &bar_card_positions
                icon: outside
                indicator: 'off'
                name: outside
              severity: &bar_card_severity
                - color: '#9da0a2'
                  from: 0
                  to: 59
                - color: '#6d2525'
                  from: 60
                  to: 100
              entity_row: true
              entities:
                - entity: sensor.processor_use
                  name: Processor
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.processor_use

                - entity: sensor.processor_temperature
                  name: Temperature
                  icon: mdi:thermostat

                - entity: sensor.memory_use_percent
                  name: Memory
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.memory_use_percent
                - entity: sensor.disk_use_percent
                  name: Disk used
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.disk_use

            - type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Restart
                  icon: mdi:reload
                  tap_action:
                    action: call-service
                    confirmation:
                      text: Are you sure you want to restart?
                    service: homeassistant.restart
                  template: icon_name

                - type: custom:button-card
                  name: Reload YAML
                  icon: mdi:reload
                  tap_action:
                    action: call-service
                    service: browser_mod.sequence
                    service_data:
                      sequence:
                        - service: browser_mod.notification
                          data:
                            message: Reload all YAML configuration...
                        - service: homeassistant.reload_all
                  template: icon_name

        #################################################
        #                                               #
        #                Raspberry Docker               #
        #                                               #
        #################################################
        - type: entities
          view_layout:
            grid-area: docker
          title: Raspberry Docker
          show_header_toggle: false
          card_mod:
            class: header

          entities:
            - entity: binary_sensor.raspberry_docker
              icon: si:docker
              secondary_info: last-changed
              name: Status

            - entity: switch.watchtower

            - type: attribute
              entity: sensor.rpi_monitor_pidocker
              attribute: up_time
              name: Uptime
              icon: mdi:update

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              # unit_of_measurement: '%'
              positions: *bar_card_positions
              severity: *bar_card_severity
              entity_row: true
              entities:
                - entity: sensor.rpi_cpu_use_pidocker
                  name: Processor
                  icon: mdi:chip
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.rpi_cpu_use_pidocker

                - entity: sensor.rpi_temp_pidocker
                  name: Temperature
                  icon: mdi:thermostat

                - entity: sensor.template_pidocker_mem
                  name: Memory 4GB
                  icon: mdi:memory
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.template_pidocker_mem

                - entity: sensor.rpi_used_pidocker
                  name: SD used 32GB
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.rpi_used_pidocker

            - type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Reboot RPI
                  icon: mdi:reload
                  tap_action:
                    action: call-service
                    confirmation:
                      text: Are you sure you want to restart?
                    service: script.restart_pi_docker
                  template: icon_name

                - type: custom:button-card
                  name: Purge logs
                  icon: mdi:archive-remove
                  tap_action:
                    action: call-service
                    service: script.purge_dockerlog
                  template: icon_name

        #################################################
        #                                               #
        #                CONTAINERS                     #
        #                                               #
        #################################################

        - type: entities
          view_layout:
            grid-area: containers
          title: Containers
          show_header_toggle: false
          card_mod:
            class: header
            # no border on last card
            style: |
              ha-card {
                border: none !important;
              }
              #states {
                text-transform: capitalize !important;
              }

          entities:
            - entity: sensor.docker_portainer
              name: Portainer
              secondary_info:
                attribute: status
            - entity: sensor.docker_homebridge
              name: Hombridge
              secondary_info:
                attribute: status
            - entity: sensor.docker_watchtower
              name: Watchtower
              secondary_info:
                attribute: status
            - entity: sensor.docker_unifi_controller
              name: Unifi Controller
              secondary_info:
                attribute: status
            - entity: sensor.docker_hadockermon
              name: HA-Dockermon
              secondary_info:
                attribute: status
