action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: MBPro Server
    style: >
      --popup-max-width: 450px;
    card_mod:
      style:
        .: |

        layout-card:
          $grid-layout$:
            # card divider border
            .: |
              #root > * {
                margin: 0px !important;
              }
              @media (max-width: 450px), (max-height: 500px) {
                #root {
                  display: block !important;
                }
              }

            hui-entities-card:
              $: |
                ha-card {
                  animation: border 1s forwards;
                  border-radius: 0;
                }
                /* phone */
                @media screen and (max-width: 800px) {
                  ha-card {
                    animation: none;
                  }
                }
              $hui-horizontal-stack-card:
                # horizontal bottom buttons
                $: |
                  #root {
                    justify-content: space-evenly;
                    margin-top: 1.7em;
                  }
    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 450px
        grid-template-areas: |
          "hass"
        mediaquery:
          #phone
          '(max-width: 800px)':
            grid-template-columns: 1fr
            grid-template-rows: repeat(1, 1fr)
            grid-template-areas: |
              "hass"

      cards:
        #################################################
        #                                               #
        #                HOME ASSISTANT                 #
        #                                               #
        #################################################

        - type: entities
          view_layout:
            grid-area: hass
          title: ' '
          show_header_toggle: false
          card_mod:
            class: header
          entities:
            - entity: binary_sensor.macbookpro
              name: Active
              state_color: true

            - entity: sensor.mbproserver_connection_type
              name: Connection

            # - entity: sensor.mbpro_ip
            #   name: IP

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: &bar_card_positions
                icon: outside
                indicator: 'off'
                name: outside
              severity: &bar_card_severity
                - color: '#9da0a2'
                  from: 0
                  to: 59
                - color: '#9da0a2'
                  from: 60
                  to: 100
              entity_row: true
              entities:
                - entity: sensor.mbpro_cpu
                  name: Processor

                - entity: sensor.mbpro_mem
                  name: Memory

                - entity: sensor.mbproserver_storage
                  name: Storage

            - type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Lock
                  icon: mdi:lock
                  tap_action:
                    action: call-service
                    service: shell_command.lock_mbpro
                  template: icon_name

                - type: custom:button-card
                  name: Sleep
                  icon: mdi:power-sleep
                  tap_action:
                    action: call-service
                    service: shell_command.sleep_mbpro
                  template: icon_name
          footer:
            type: custom:mini-graph-card
            # name: Speedtest
            tap_action:
              action: call-service
              service: homeassistant.update_entity
              service_data:
                entity_id: sensor.mbpro_cpu
            entities:
              - entity: sensor.mbpro_cpu
                name: Processor
                color: '#00bb33'
              - entity: sensor.mbpro_mem
                name: Memory
                show_state: false
                color: '#2196f3'
                y_axis: secondary
            hours_to_show: 48
            hour24: true
            line_width: 3
            animate: true
            # upper_bound_secondary: 100
            show:
              name: false
              icon: false
              state: false
              legend: false
              fill: fade
              labels: true
              labels_secondary: false
              average: false
              extrema: false
              points: hover
