action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: NAS
    style: >
      --popup-max-width: calc(385px + 385px + 385px);
      --ha-card-border-radius: 0;
    card_mod:
      style:
        layout-card:
          $grid-layout$:
            # card divider border
            .: |
              #root {
                  margin: -24px 0 !important;
              }
            hui-entities-card:
              $: |
                .card-content {
                  padding: var(--tablet-popup-content-padding);
                  padding-bottom: 0.8em;
                }
                ha-card {
                  border-right: 1.5px solid rgba(0, 0, 0, 0.2);
                  border-radius: 0;
                  transition: none;
                }
                /* portrait */
                @media screen and (max-width: 1200px) {
                  ha-card {
                    border-right: none;
                    border-bottom: 1.5px solid rgba(0, 0, 0, 0.2);
                  }
                }
              $hui-horizontal-stack-card:
                # horizontal bottom buttons
                $: |
                  #root {
                    justify-content: space-evenly;
                    margin-top: 1.7em;
                    max-width: 82vw; /* iphonex */
                  }
    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 385px 385px 385px
        grid-template-rows: 1fr
        grid-template-areas: |
          "hass docker nas"
        mediaquery:
          #portrait
          '(max-width: 1200px)':
            grid-template-columns: 1fr
            grid-template-rows: repeat(3, 1fr)
            grid-template-areas: |
              "hass"
              "docker"
              "nas"
      cards:
        ### HOME ASSISTANT

        - type: entities
          view_layout:
            grid-area: hass
          show_header_toggle: false
          entities:
            - entity: sensor.current_version
              name: Installed
              icon: mdi:home-assistant

            - entity: sensor.home_assistant_versions
              name: Latest

            - entity: sensor.database_size
              name: Database
              icon: mdi:database

            - entity: sensor.uptime
              name: Last reboot

            - entity: input_boolean.notify_visible
              name: Notifications

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: &bar_card_positions
                icon: outside
                indicator: 'off'
                name: outside
              severity: &bar_card_severity
                - color: '#636363'
                  from: 0
                  to: 89
                - color: '#6d2525'
                  from: 90
                  to: 200
              entity_row: true
              entities:
                - entity: sensor.processor_use
                  name: Processor
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.processor_use

                - entity: sensor.memory_use_percent
                  name: Memory
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.memory_use_percent

            - type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Home Assistant
                  icon: mdi:reload
                  tap_action:
                    services: |
                      [[[
                        return `[[[
                          hass.callService('persistent_notification', 'create', {
                            message: 'Restarting Home Assistant...'
                          });
                          hass.callService('homeassistant', 'restart');
                        ]]]`
                      ]]]
                  template: icon_name

                - type: custom:button-card
                  name: Theme
                  icon: mdi:reload
                  tap_action:
                    services: |
                      [[[
                        return `[[[
                          hass.callService('persistent_notification', 'create', {
                            message: 'Restarting Theme Service...'
                          });
                          hass.callService('frontend', 'reload_themes');
                        ]]]`
                      ]]]
                  template: icon_name

        ### DOCKER

        - type: entities
          view_layout:
            grid-area: docker
          title: Docker
          state_color: true
          show_header_toggle: false
          card_mod:
            class: header
          entities:
            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: *bar_card_positions
              severity: *bar_card_severity
              entity_row: true
              entities:
                - entity: sensor.docker_1cpu
                  name: Processor

                - entity: sensor.docker_memory_percent
                  name: Minne

            - entity: sensor.docker_containers_total
              name: Containrar Totalt

            - entity: sensor.docker_containers_running
              name: Containrar Körs

            - entity: sensor.docker_containers_paused
              name: Containrar Pausade

            - entity: sensor.docker_containers_stopped
              name: Containrar Stoppade

            - entity: switch.docker_transmission_seed

          footer:
            type: custom:apexcharts-card
            layout: minimal
            graph_span: 1h
            locale: se
            apex_config:
              chart:
                fontFamily: var(--primary-font-family)
                height: 135px
              tooltip:
                style:
                  fontSize: 14px
                x:
                  show: true
                  format: dddd HH:mm
              xaxis:
                crosshairs:
                  show: false
              legend:
                fontSize: 14px
                fontWeight: 400
                itemMargin:
                  horizontal: 25
                formatter: |
                  EVAL: (seriesName, opts) => {
                    var arr = opts.w.globals.series[opts.seriesIndex],
                      value = arr[arr.length - 1],
                      convert = (value/1024).toFixed(2);
                    return value == null
                      ? seriesName : value < 1024 ? `${Math.round(value)} kB/s`
                      : `${convert} MB/s`;
                  }
                markers:
                  width: 26
                  height: 23
                  customHTML:
                    - 'EVAL:() => {return `<ha-icon icon="mdi:arrow-down-bold" style="--mdc-icon-size: 23px;"></ha-icon>`}'
                    - 'EVAL:() => {return `<ha-icon icon="mdi:arrow-up-bold" style="--mdc-icon-size: 23px;"></ha-icon>`}'
                  fillColors:
                    - none
                    - none
              fill:
                type: gradient
                gradient:
                  type: vertical
                  opacityFrom: 0.8
                  opacityTo: 0
                  stops:
                    - 0
                    - 99
                    - 100
              stroke:
                width: 3
            all_series_config:
              type: area
              fill_raw: last
            series:
              - entity: sensor.nas_download_throughput
                name: Ned
                color: green
              - entity: sensor.nas_upload_throughput
                name: Upp
                color: '#385581'

        ### NAS

        - type: entities
          view_layout:
            grid-area: nas
          title: Synology DS918+
          show_header_toggle: false
          card_mod:
            class: header
            # no border on last card
            style: |
              ha-card {
                border: none !important;
              }
          entities:
            - entity: sensor.template_nas_status

            - entity: binary_sensor.nas_security_status
              name: Säkerhetsstatus

            - entity: sensor.nas_volume_1_average_disk_temp

            - entity: sensor.last_boot
              name: Senast omstart

            - entity: update.nas_dsm_update
              icon: mdi:package-up
              name: Uppdatering

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: *bar_card_positions
              severity: *bar_card_severity
              entity_row: true
              entities:
                - entity: sensor.processor_use
                  name: Processor
                  icon: mdi:chip
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.processor_use

                - entity: sensor.memory_use_percent
                  name: Minne - 4GB
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.memory_use_percent

                - entity: sensor.disk_use_percent
                  name: Lagring - 10.5TB
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.disk_use_percent

            - type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Starta om
                  icon: mdi:restart-alert
                  confirmation:
                    text: Är du säker på att du vill starta om NAS?
                  tap_action:
                    action: call-service
                    service: browser_mod.sequence
                    service_data:
                      sequence:
                        - service: browser_mod.notification
                          data:
                            message: Startar om NAS...
                        - service: button.press
                          data:
                            entity_id: button.nas_reboot
                  template: icon_name

                - type: custom:button-card
                  name: Stäng av...
                  icon: mdi:alert
                  confirmation:
                    text: Är du säker på att du vill stänga av NAS?
                  tap_action:
                    action: call-service
                    service: browser_mod.sequence
                    service_data:
                      sequence:
                        - service: browser_mod.notification
                          data:
                            message: Stänger av NAS...
                        - service: button.press
                          data:
                            entity_id: button.nas_shutdown
                  template: icon_name
