action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Platta
    card_mod:
      style:
        #popup header
        .:
    content:
      type: vertical-stack
      cards:
        - type: entities
          state_color: true
          card_mod:
            class: content
          entities:

            - entity: switch.galaxy_tab_a_screen
              secondary_info: last-changed

            - type: custom:slider-entity-row
              entity: number.galaxy_tab_a_screen_brightness
              name: Ljusstyrka
              icon: mdi:brightness-6
              hide_state: false
              card_mod:
                style:
                  # full width slider
                  hui-generic-entity-row$: |
                    div {
                      flex: auto !important;
                    }

            - entity: switch.galaxy_tab_a_screensaver

            - entity: binary_sensor.galaxy_tab_a_plugged_in

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: &bar_card_positions
                icon: outside
                indicator: 'off'
                name: outside
              severity:
                - color: '#6d2525'
                  from: 0
                  to: 89
                - color: '#303435'
                  from: 90
                  to: 999
              entity_row: true
              entities:

                - entity: sensor.galaxy_tab_a_battery
                  icon: mdi:battery
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.galaxy_tab_a_battery_level

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions: *bar_card_positions
              severity:
                - color: '#6d2525'
                  from: 90
                  to: 999
              entity_row: true
              entities:

                - entity: sensor.template_fullykiosk_memory
                  name: Minne - 2GB
                  icon: mdi:memory
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.template_fullykiosk_memory

                - entity: sensor.template_fullykiosk_storage
                  name: Lagring - 32GB
                  icon: mdi:sd
                  tap_action:
                    action: call-service
                    service: homeassistant.update_entity
                    service_data:
                      entity_id: sensor.template_fullykiosk_storage

        - type: custom:mod-card
          card_mod:
            style:
              hui-horizontal-stack-card$: |
                #root {
                  justify-content: space-evenly !important;
                  padding: var(--tablet-popup-button-padding);
                }
          card:
            type: horizontal-stack
            cards:
              - type: custom:button-card
                name: Startsidan
                icon: mdi:reload
                tap_action:
                  action: call-service
                  service: browser_mod.sequence
                  service_data:
                    sequence:
                      - service: browser_mod.notification
                        data:
                          message: Laddar om startsidan...
                      - service: button.press
                        data:
                          entity_id: button.galaxy_tab_a_load_start_url
                template: icon_name

              - type: custom:button-card
                name: Hela appen
                icon: mdi:reload
                tap_action:
                  action: call-service
                  service: browser_mod.sequence
                  service_data:
                    sequence:
                      - service: browser_mod.notification
                        data:
                          message: Startar om Fully Kiosk Browser...
                      - service: button.press
                        data:
                          entity_id: button.galaxy_tab_a_restart_browser
                template: icon_name
