action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Roidmi EVE Plus
    style: |
      --popup-max-width: calc(395px + 505px + 395px);
      --tablet-popup-button-padding: 0.1em 2em 1.8em 2em;
      --swiper-pagination-color: rgb(255, 165, 0);
      --swiper-navigation-size: 2em;
    card_mod:
      style:
        .: |

        # card divider border
        layout-card$grid-layout$:
          .: |
            #root > * {
              margin: 0px !important;
            }
          hui-entities-card:
            $: |
              ha-card {
                border-right: 0.1vw solid rgba(58, 69, 73, 0.2);
                border-radius: 0;
                transition: none;
              }

              /* portrait */
              @media screen and (max-width: 1400px) {
                ha-card {
                  border-right: none;
                  border-bottom: 0.1vw solid rgba(58, 69, 73, 0.2);
                }
              }

    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 0 395px 505px 395px 0
        grid-template-rows: 1fr
        grid-template-areas: |
          ". info map sensor ."
        mediaquery:
          #phone
          '(max-width: 800px)':
            grid-template-columns: 1fr
            grid-template-areas: |
              "info"
              "map"
              "sensor"
      cards:
        ### SUMMARY

        - type: entities
          view_layout:
            grid-area: info
          title: Summary
          show_header_toggle: false
          card_mod:
            class: header
            # style: |
            #   .card-content {
            #     padding: var(--tablet-popup-content-padding);
            #     padding-bottom: 0;
            #   }
            #   .card-header {
            #     padding: 0 1.5vw  !important;
            #   }
          entities:
            - entity: sensor.vacuum_status_fix
              name: Roidmi EVE plus
              icon: phu:roborock
              secondary_info:
                entity: sensor.roidmi_v60_029d_battery_level
                postfix: ' %'
                prefix: 'Battery: '
            - entity: sensor.vacuum_fault
              secondary_info:
                entity: sensor.vacuum_position
                prefix: 'Position: '
            # - sensor.vacuum_fan_speed
            # - sensor.vacuum_sweep_mode
            - binary_sensor.vacuum_mop
            - type: divider
            - input_boolean.vacuum_double_clean
            - input_boolean.vacuum_edge_sweep
            - input_select.vacuum_mode
            - input_select.vacuum_sweep_type
            - input_select.vacuum_water_level

            - type: custom:mod-card
              card_mod:
                style:
                  # horizontal bottom buttons
                  hui-horizontal-stack-card$: |
                    #root {
                      justify-content: space-between!important;
                      padding: 1em;
                    }
              card:
                type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: vacuum.roidmi_eve
                    icon: mdi:play-pause
                    tap_action:
                      action: call-service
                      service: >
                        [[[
                          return `[[[
                            return entity.state === 'docked' || entity.state === 'paused'
                              ? 'vacuum.start'
                              : 'vacuum.pause';
                          ]]]`
                        ]]]
                      service_data:
                        entity_id: vacuum.roidmi_eve
                    template: icon_only

                  - type: custom:button-card
                    entity: vacuum.roidmi_eve
                    icon: mdi:battery-charging
                    tap_action:
                      action: call-service
                      service: vacuum.return_to_base
                      service_data:
                        entity_id: vacuum.roidmi_eve
                    template: icon_only

                  - type: custom:button-card
                    icon: mdi:bell
                    tap_action:
                      action: call-service
                      service: script.vacuum_find_robot
                    template: icon_only

                  - type: custom:button-card
                    icon: mdi:delete-empty
                    tap_action:
                      action: call-service
                      service: script.vacuum_empty_bin
                    template: icon_only

        ### MAP

        - !include vacuum_roidmi.yaml

        ## SETTINGS

        - type: entities
          view_layout:
            grid-area: sensor
          title: Settings
          show_header_toggle: false
          card_mod:
            class: header
            style: |
              ha-card {
                border-left: 0.1vw solid rgba(58, 69, 73, 0.2);
                border-right: none !important;
              }
              /* portrait */
              @media screen and (max-width: 1400px) {
                ha-card {
                  border: none;
                }
              }
          entities:
            - input_number.vacuum_volume
            - input_boolean.vacuum_mute
            - input_boolean.vacuum_lidar_collision
            - input_boolean.vacuum_led_switch
            - input_boolean.vacuum_auto_boost
            - sensor.vacuum_on
            - sensor.vacuum_cleaned_area
            - sensor.vacuum_cleaning_time
            - sensor.vacuum_total_cleaned_area
            - sensor.vacuum_total_cleaning_time
            - sensor.vacuum_cleaning_count
