#-
#   __ _           _
#  / _(_)_ __   __| |_ __ ___  _   _
# | |_| | '_ \ / _` | '_ ` _ \| | | |
# |  _| | | | | (_| | | | | | | |_| |
# |_| |_|_| |_|\__,_|_| |_| |_|\__, |
#                              |___/
#- from github.com/ngocjohn/hass-config
#
homeassistant:
  customize:
    device_tracker.viet_ngoc_samsung:
      entity_picture: /local/img/samsung-z-flip.png
    device_tracker.amg_43_parking_location:
      entity_picture: /local/img/benz_amg.png

template:
  - triggers:
      - alias: 'Viet Ngoc disconnected from Android Auto'
        trigger: state
        entity_id: binary_sensor.viet_ngoc_samsung_android_auto
        from: 'on'
        to: 'off'
        id: androidauto
      - alias: 'MB Bluetooth disconnected'
        trigger: state
        entity_id: sensor.viet_ngoc_samsung_bluetooth_connection
        to: '0'
        variables:
          disconnect_from_mb: >
            {% set mb_ble = "48:F0:7B:3A:E9:8B (MB Bluetooth 61471)" %}
            {{ mb_ble is in trigger.from_state.attributes.connected_paired_devices }}
    conditions:
      - condition: or
        conditions:
          - condition: trigger
            id:
              - androidauto
          - condition: template
            value_template: '{{ disconnect_from_mb }}'
    actions:
      - variables:
          notify_action: notify.mobile_app_viet_ngoc_samsung
          geocoded: sensor.viet_ngoc_samsung_geocoded_location
          device_tracker: device_tracker.viet_ngoc_samsung
      - action: '{{ notify_action }}'
        data:
          message: 'request_location_update'
      - delay:
          seconds: 3
    sensor:
      - unique_id: 9c9da226-77f1-4366-9d0a-c778941fd61b
        name: AMG 43 Geocoded Location
        state: '{{ states(geocoded) }}'
        attributes:
          latitude: "{{ state_attr(device_tracker, 'latitude') }}"
          longitude: "{{ state_attr(device_tracker, 'longitude') }}"
          gps_accuracy: "{{ state_attr(device_tracker, 'gps_accuracy') }}"
