media_player:
  - platform: universal ### CURRENTLY PLAYING ###
    name: Currently Playing
    unique_id: currently_playing
    children:
      - media_player.mass_universal_airplay
      - media_player.spotifyplus_ngoc_nguyen
      - media_player.living_room_tv
      - media_player.bedroom_tv
  - platform: universal ### CURRENTLY PLAYING ###
    name: Homepod Airplay Group
    unique_id: homepod_airplay_media
    children:
      - media_player.office
      - media_player.bathroom_homepod
      - media_player.bedroom_homepod
      - media_player.living_room

  - platform: universal ### CURRENTLY PLAYING ###
    name: Mass Universal Airplay
    unique_id: mass_universal_airplay
    children:
      - media_player.office_homepod
      - media_player.bathroom
      - media_player.bedroom
      - media_player.living_room_2
template:
  - select:
      - name: conditional_media
        state: >-
          {% set recently_added = 'Recently added' %}
          {% set paused_timeout_minutes = 2 %}
          {% set idled_timeout_minutes = 1 %}
          {% set media_players = expand('group.conditional_media') %}

          {% macro media(state) %}
          {% set state = media_players | selectattr('state','eq',state) | list %}
          {% set last_changed = recently_added if state | length == 0 else state | map(attribute='last_changed') | list | max %}
            {{ state | selectattr('last_changed','eq', last_changed) | map(attribute='name') | list | join }}
          {% endmacro %}

          {% set playing = media_players | selectattr('state','eq','playing') | list %}
          {% set timeout_playing = False if playing | length == 0 else (as_timestamp(now()) - as_timestamp(playing | map(attribute='last_changed') | list | max)) < paused_timeout_minutes * 60 %}

          {% set paused = media_players | selectattr('state','eq','paused') | list %}
          {% set timeout_paused = False if paused | length == 0 else (as_timestamp(now()) - as_timestamp(paused | map(attribute='last_changed') | list | max)) < paused_timeout_minutes * 60 %}

          {% set idled = media_players | selectattr('state','eq','idle') | list %}
          {% set timeout_idled = False if idled | length == 0 else (as_timestamp(now()) - as_timestamp(idled | map(attribute='last_changed') | list | max)) < idled_timeout_minutes * 60 %}

          {% if playing %}
            {{ media('playing') if timeout_playing else media('paused') if timeout_paused else media('playing') }}
          {% elif paused %}
            {{ media('paused') if timeout_paused else media('idle') if timeout_idled else recently_added }}
          {% elif idled %}
            {{ media('idle') if timeout_idled else recently_added }}
          {% else %}
            {{ recently_added }}
          {% endif %}
        options: >
          {% set recently_added = ['Recently added'] %}
          {% set media_players = expand('group.conditional_media') %}
          {{ recently_added + media_players | map(attribute='name') | list }}
        select_option:
          service: select.select_option
          target:
            entity_id: select.conditional_media
          data:
            option: >
              {{ option }}
