# Bedroom TV ###
media_player:
  - platform: universal
    name: Bedroom TV
    device_class: tv
    unique_id: bedroom_tv
    children:
      - media_player.bedroom_samsung_television
      - media_player.bedroom_shield_android_tv
    active_child_template: >
      {% if state_attr("media_player.bedroom_samsung_television", "source") in ['hdmi3', 'Shield TV']  %}
        media_player.bedroom_shield_android_tv
      {% else %}
        media_player.bedroom_samsung_television
      {% endif %}
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: media_player.bedroom_samsung_television
      turn_off:
        service: media_player.turn_off
        target:
          entity_id: media_player.bedroom_samsung_television
