########################################
#   LIVING ROOM MEDIA                  #
########################################
# LIVING ROOM TV ###
media_player:
  - platform: universal
    name: Living Room TV
    device_class: tv
    unique_id: living_room_tv
    children:
      - media_player.atv
      - media_player.sony_tv_combined
    active_child_template: >
      {% if state_attr("media_player.sony_bravia_tv", "source") in ['HDMI 2', 'Apple TV']  %}
        media_player.atv
      {% else %}
        media_player.sony_tv_combined
      {% endif %}
    commands:
      turn_on:
        service: remote.turn_on
        target:
          entity_id: remote.sony_bravia_tv
      turn_off:
        service: script.atv_sleep
        data: {}
