########################################
#   DOCKER RASPBERRY PI                #
########################################
template:
  - binary_sensor:
      ########################################
      #           RASPBERRY SYSTEM           #
      ########################################
      - unique_id: raspberry_docker
        name: Raspberry Docker
        icon: mdi:raspberry-pi
        state: >
          {{ has_value('sensor.rpi_monitor_pidocker') }}
        device_class: running
        attributes:
          uptime: >
            {{ state_attr('sensor.rpi_monitor_pidocker', 'up_time') }}
          IP: >
            {% if has_value('sensor.rpi_monitor_pidocker') %}
              {{ state_attr('sensor.rpi_monitor_pidocker', 'networking')['eth0'].IP }}
            {% endif %}
          last_reboot: >
            {{ as_timestamp(state_attr('sensor.rpi_monitor_pidocker', 'last_update')) | timestamp_custom('%d.%m.%y at %H:%M') }}
  - sensor:
      - unique_id: pidocker_mem
        state: >
          {{ ((state_attr('sensor.rpi_monitor_pidocker', 'memory').free_mb | int) / (state_attr('sensor.rpi_monitor_pidocker', 'memory').size_mb | int) * 100) | int }}
