command_line:
  - sensor:
      name: mbpro_cpu
      unique_id: 'd2c3b24f-ff0e-4776-ab94-418731b510bf'
      command: !secret mbpro_cpu
      unit_of_measurement: '%'
      value_template: >
        {{ (100 - value[:-1] | float(default=0)) | round(1) }}
      scan_interval: 120

  - sensor:
      name: mbpro_mem
      unique_id: 'ad232858-7c85-4523-8c5a-24409dcf5f7c'
      command: !secret mbpro_mem
      unit_of_measurement: '%'
      scan_interval: 120

  - sensor:
      name: mbpro_uptime
      unique_id: '27ffe3b0-8147-4709-a749-f3eaabd65404'
      command: !secret mbpro_uptime
      value_template: >
        {% set timestamp = value[:-1] | int(default=0) %}
        {% set year = 120 * 365 %}
        {{ timestamp | timestamp_local if (as_timestamp(now()) - timestamp) < year else None}}
      scan_interval: 120

  - sensor:
      name: mbpro_ip
      command: !secret mbpro_ip
      scan_interval: 86400

template:
  - binary_sensor:
      - name: 'MacbookPro'
        unique_id: '1bd2146a-71b3-4b5b-b86a-14c732042731'
        device_class: running
        icon: ios:desktopcomputer
        state: "{{ is_state_attr('binary_sensor.mbproserver_active', 'Sleeping', false ) }}"

homeassistant:
  customize:
    sensor.mbpro_cpu:
      friendly_name: Processor
      icon: mdi:chip
    sensor.mbpro_mem:
      friendly_name: Free Memory
      icon: mdi:memory
    sensor.mbpro_uptime:
      friendly_name: Macbook uptime
      icon: mdi:update
      device_class: timestamp
