########################################
#   BEDROOM MEDIA                      #
########################################
media_player:
  - platform: media_player_template
    media_players:
      bedroom_tv: ### BED ROOM TEMPLATE ###
        friendly_name: Bedroom TV
        unique_id: bedroom_media
        device_class: tv
        ###### ATTRIBUTES ######
        current_is_muted_template: "{{ state_attr('media_player.shield', 'is_volume_muted') }}"
        current_volume_template: "{{ state_attr('media_player.shield', 'volume_level') }}"
        title_template: "{{ state_attr('media_player.shield', 'media_title') }}"
        album_template: "{{ state_attr('media_player.shield', 'media_album_name') }}"
        artist_template: "{{ state_attr('media_player.shield', 'media_artist') }}"
        current_source_template: "{{ state_attr('media_player.shield_android_tv', 'source') }}"
        current_position_template: "{{ state_attr('media_player.shield', 'media_position') }}"
        media_duration_template: "{{ state_attr('media_player.shield', 'media_duration') }}"
        media_content_type_template: "{{ state_attr('media_player.shield', 'media_content_type') }}"
        media_image_url_template: >
          {% if is_state_attr('media_player.shield_android_tv', 'app_name', 'YouTube') -%}
            {{ states('sensor.youtube_thumbnail') }}
          {%- else -%}
            {{ state_attr('media_player.shield_android_tv', 'entity_picture') }}
          {%- endif %}
        value_template: >
          {% if is_state("media_player.shield_android_tv", "off") -%}
            off
          {%- else -%}
            {{ states('media_player.shield_android_tv') }}
          {%- endif %}
        turn_on:
          service: media_player.turn_on
          data: {}
          target:
            entity_id: media_player.shield_android_tv
        turn_off:
          service: media_player.turn_off
          data: {}
          target:
            entity_id: media_player.shield_android_tv
        volume_up:
          service: media_player.volume_up
          data: {}
          target:
            entity_id: media_player.shield
        volume_down:
          service: media_player.volume_down
          data: {}
          target:
            entity_id: media_player.shield
        play:
          service: media_player.media_play
          data: {}
          target:
            entity_id: media_player.shield
        pause:
          service: media_player.media_pause
          data: {}
          target:
            entity_id: media_player.shield
        stop:
          service: media_player.media_stop
          data: {}
          target:
            entity_id: media_player.shield
        next:
          service: media_player.media_next_track
          data: {}
          target:
            entity_id: media_player.shield
        previous:
          service: media_player.media_previous_track
          data: {}
          target:
            entity_id: media_player.shield
        set_volume:
          service: media_player.volume_set
          data:
            entity_id: media_player.shield
            volume_level: '{{ volume | float }}'
        mute:
          service: media_player.volume_mute
          data:
            is_volume_muted: false
          target:
            entity_id: media_player.shield
        ###### SOURCE ######
        inputs:
          Netflix:
            service: media_player.select_source
            data:
              source: Netflix
            target:
              entity_id: media_player.shield_android_tv
          YouTube:
            service: media_player.select_source
            data:
              source: YouTube
            target:
              entity_id: media_player.shield_android_tv
          Kodi:
            service: media_player.select_source
            data:
              source: Kodi
            target:
              entity_id: media_player.shield_android_tv
          Spotify:
            service: media_player.select_source
            data:
              source: Spotify
            target:
              entity_id: media_player.shield_android_tv
  ### BEDROOM UNIVERSAL ###
  - platform: universal
    name: ShieldTV Kodi
    unique_id: shieldtv_kodi
    device_class: tv
    children:
      - media_player.bedroom_kodi
      - media_player.bedroom_tv
    commands:
      turn_on:
        service: media_player.turn_on
        data: {}
        target:
          entity_id: media_player.shield_android_tv
      turn_off:
        service: media_player.turn_off
        data: {}
        target:
          entity_id: media_player.shield_android_tv
