switch:
  - platform: template
    switches:
      macbook:
        value_template: "{{ is_state('binary_sensor.macbook_air_active', 'on') }}"
        unique_id: macbook_switch
        turn_on:
          service: script.macbook_air_login
        turn_off:
          service: shell_command.lock_mac

      # VOCOLINC DIFFUSER
      office_humidifier:
        unique_id: sw_office_humid
        value_template: "{{ is_state('fan.vocolinc_rpl_188bce_ripple', 'on') }}"
        turn_on:
          service: fan.turn_on
          target:
            entity_id: fan.vocolinc_rpl_188bce_ripple
        turn_off:
          service: fan.turn_off
          target:
            entity_id: fan.vocolinc_rpl_188bce_ripple
      bedroom_humidifier:
        unique_id: sw_bedroom_humid
        value_template: "{{ is_state('fan.bedroom_ripple_ripple', 'on') }}"
        turn_on:
          service: fan.turn_on
          target:
            entity_id: fan.bedroom_ripple_ripple
        turn_off:
          service: fan.turn_off
          target:
            entity_id: fan.bedroom_ripple_ripple
