card:
  type: entities
  entities:
    - type: custom:multiple-entity-row
      entity: sensor.unifi_bedroom_ap
      name: Bedroom AP
      show_entity_picture: true
      show_state: false
      secondary_info:
        attribute: Uptime
      entities:
        - entity: sensor.unifi_bedroom_ap_cpu
          name: CPU
        - entity: sensor.unifi_bedroom_ap_ram
          name: RAM
        - icon: mdi:restart
          tap_action:
            action: call-service
            confirmation: true
            service: button.press
            service_data:
              entity_id: button.ap_bedroom_restart
    - type: custom:multiple-entity-row
      entity: sensor.unifi_bedroom_ap
      icon: mdi:devices
      name: 'Total Clients'
      show_state: false
      secondary_info:
        entity: sensor.unifi_bedroom_ap
      entities:
        - entity: sensor.unifi_bedroom_ap_2_4ghz_clients
          name: 2.4GhZ
          unit: ' '
        - entity: sensor.unifi_bedroom_ap_5ghz_clients
          name: 5GhZ
          unit: ' '
        - entity: sensor.unifi_bedroom_ap_guests
          name: Guests
          unit: ' '
    - type: custom:multiple-entity-row
      entity: sensor.unifi_bedroom_ap
      name: 'Experience'
      icon: mdi:percent-outline
      show_state: false
      secondary_info:
        attribute: Score
      entities:
        - entity: sensor.unifi_bedroom_ap_2_4ghz_score
          name: 2gHz
          unit: '%'
          tap_action:
            action: none
        - entity: sensor.unifi_bedroom_ap_5ghz_score
          name: 5gHz
          unit: '%'
          tap_action:
            action: none
    - type: custom:mini-graph-card
      entities:
        - entity: sensor.unifi_bedroom_ap_score
      group: true
      font_size: 14px
      hours_to_show: 24
      show:
        icon: false
        graph: false
        name: false
        state: false
        extrema: true
        average: true
attributes:
  label: Bedroom
