type: custom:local-conditional-card
default: show
id: landscape
card:
  type: custom:floorplan-card
  style: >
    ha-card {
      margin: 14% 0;
      background: radial-gradient(circle, rgb(255 255 255 / 14%) 27%, rgba(57,14,14,0) 61%);
      box-shadow: none;
      opacity: 0;
      animation: slide-opacity 1000ms cubic-bezier(0.4, 0, 0.2, 1) 500ms both;
      transform: translate3d(0,0,0);
      -webkit-transform: translate3d(0,0,0);
    }
    @keyframes slide-opacity {
      0% {
        transform: translateX(100%);
        opacity: 0;
      }
      100% {
        transform: translateX(0%);
        opacity: 1;
      }
    }
  config:
    image: /local/hafloor/plan_opt.svg
    stylesheet: /local/hafloor/style.css
    defaults:
      hover_action: false
      tap_action: false
    # log_level: info
    # console_log_level: info
    rules: !include_dir_merge_list /config/UI/floorplan/
