type: custom:local-conditional-card
default: hide
id: ymovie
card:
  type: vertical-stack
  cards:
    - type: custom:mushroom-chips-card
      chips:
        - type: template
          icon: mdi:close
          icon_color: rgb(139, 51, 51)
          tap_action:
            action: fire-dom-event
            local_conditional_card:
              action: toggle
              ids:
                - landscape
                - ymovie
    - type: custom:gap-card
      height: 26
    - type: custom:mod-card
      card_mod:
        style: |
          ha-card {
            background: rgba(115, 115, 115, 0.2);
            border-start-start-radius: 1vw;
            border-start-end-radius: 1vw;
            overflow: hidden;
            opacity: 0;
            animation: slide-opacity 1000ms cubic-bezier(0.4, 0, 0.2, 1) 500ms both;
          }
          @keyframes slide-opacity {
            0% {
              transform: translateX(100%);
              opacity: 0;
            }
            100% {
              transform: translateX(0%);
              opacity: 1;
            }
          }
      card:
        type: custom:tabbed-card
        styles: # global styles applied to all tabs
          --mdc-theme-primary: 'rgba(250, 250, 250, 0.75)'
          --mdc-tab-text-label-color-default: '#97989c'
          --mdc-typography-button-font-size: 17px;
        tabs:
          - card:
              type: iframe
              url: https://ymovie.streamcinema.cz/#/scc/browse/Movies
              aspect_ratio: 100%
            attributes:
              label: Movies
              icon: mdi:movie-open-star
          - card:
              type: iframe
              url: https://ymovie.streamcinema.cz/#/scc/browse/Series
              aspect_ratio: 100%
            attributes:
              label: Series
              icon: mdi:television

          - card:
              type: iframe
              url: https://ymovie.streamcinema.cz/#/scc/browse/Popular-Movies
              aspect_ratio: 100%
            attributes:
              label: Popular
              icon: mdi:star

