#################################################
#                                               #
#                    DEVICES                    #
#                                               #
#################################################

- type: grid
  title: Devices
  view_layout:
    grid-area: devices
  columns: 2
  cards:
    # APPLE TV
    - type: custom:decluttering-card
      template: grid_atv

    # Samsung TV
    - type: custom:decluttering-card
      template: grid_samsung

    # PLAYSTATION
    - type: custom:decluttering-card
      template: grid_playstation

    # HOMEPODS
    - type: custom:decluttering-card
      template: grid_homepods

    # TEST

    # - type: custom:button-card
    #   entity: input_button.assist
    #   name: device 1
    #   template:
    #     - test_template

    # - type: custom:button-card
    #   entity: input_button.assist
    #   name: device 2
    #   template:
    #     - test_template
