#################################################
#                                               #
#      FLOORPLAN MAX RESOLUTION                 #
#                                               #
#################################################
- type: grid
  view_layout:
    grid-area: floorplan
    show:
      mediaquery: '(min-width: 1441px)'
  columns: 1
  cards:
    - type: 'custom:layout-card'
      layout_type: 'custom:grid-layout'
      layout:
        grid-template-columns: 1fr
        grid-template-rows: fit-content(100%)
        margin: 0
      cards:
        - type: vertical-stack
          cards:
            - !include ../../shared/hidden/movie_slide.yaml
            - !include ../../shared/hidden/floorplan_landscape.yaml
            - !include ../../shared/hidden/floorplan_portrait.yaml
            - !include ../../shared/hidden/ymovie.yaml

#################################################
#                                               #
#           FLOORPLAN PORTRAIT                  #
#                                               #
#################################################
- type: horizontal-stack
  view_layout:
    grid-area: floorplan
    show:
      mediaquery: '(max-width: 1440px)'
  cards:
    - type: custom:local-conditional-card
      default: show
      id: landscape
      card:
        type: custom:floorplan-card
        style: &style_portrait >
          ha-card {
            margin: 1% 13%;
            background: radial-gradient(circle, rgb(255 255 255 / 14%) 27%, rgba(57,14,14,0) 61%);
            box-shadow: none;
          }
          @media screen and (max-width: 1440px) {
            ha-card  {
              margin: 0 13% !important;
            }
          }
          @media screen and (max-width: 800px) {
            ha-card  {
              margin: 0 !important;
              padding-top: 3vh;
            }
          }
        config:
          image: /local/hafloor/plan_opt.svg
          stylesheet: /local/hafloor/style.css
          defaults:
            hover_action: false
            tap_action: false
          # log_level: info
          # console_log_level: info
          rules: !include_dir_merge_list /config/UI/floorplan/

    - type: custom:local-conditional-card
      default: hide
      id: portrait
      card:
        type: custom:floorplan-card
        # full_height: true
        style: *style_portrait
        # config: !include floorplan/floor_plan.yaml
        config:
          image: /local/hafloor/ip_floorplan/iphone_opt.svg
          stylesheet: /local/hafloor/style.css
          defaults:
            hover_action: false
            tap_action: false
          rules: !include_dir_merge_list /config/UI/floorplan
