#################################################
#                                               #
#                     SECURITY                  #
#                                               #
#################################################

- type: grid
  title: Security
  view_layout:
    grid-area: security
  columns: 2
  cards:
    # ALARM
    - type: custom:decluttering-card
      template: grid_alarm

    # FRONT DOOR
    - type: custom:decluttering-card
      template: grid_front_door

    # MOTION SENSORS
    - type: custom:decluttering-card
      template: grid_motion_sensors

    #  CONTACT SENSORS
    - type: custom:decluttering-card
      template: grid_contact_sensors
