#################################################
#                                               #
#      STICKY BOTTOM MENU                       #
#                                               #
#################################################

- type: custom:stack-in-card
  view_layout:
    grid-area: nav
    show:
      mediaquery: '(max-width: 800px)'
  style: |
    :host {
      margin-bottom: 0px !important;
      position: sticky !important;
      bottom: 26px;
      animation: 1.2s position ease-in-out;
      z-index: 4;
    }

    @keyframes position {
      0% { bottom: -80px; }
      20% { bottom: -80px; }
      70% { bottom: 26px; }
      90% { bottom: 24px; }
      100% { bottom: 26px; }
    }

    ha-card {
      margin-bottom: 0px !important;
      border-radius: 34px !important;
      background-color: #0000004d !important;
      backdrop-filter: blur(50px) brightness(1.6);
      -webkit-backdrop-filter: blur(50px) brightness(1.6);
      -moz-backdrop-filter: blur(50px) brightness(1.6);
      -o-backdrop-filter: blur(50px) brightness(1.6);
      -ms-backdrop-filter: blur(50px) brightness(1.6);
      box-shadow: 0px 2px 4px 0px #0000008c;
    }
  cards:
    - type: custom:mod-card
      card_mod:
        style:
          # horizontal bottom buttons
          hui-horizontal-stack-card$: |
            #root {
              justify-content: space-between !important;
              padding: 8px 8px 12px;
            }
      card:
        type: horizontal-stack
        cards:
          - type: custom:button-card
            template: icon_sticky_menu
            icon: mdi:home-circle
            tap_action:
              action: navigate
              navigation_path: /lovelace-yaml/summary
            styles:
              icon:
                - color: >
                    [[[
                        if (location.pathname === "/lovelace-yaml/summary")
                        return '#ffb300';
                    ]]]
          - type: custom:button-card
            template: icon_sticky_menu
            icon: mdi:chart-box
            tap_action:
              action: navigate
              navigation_path: /lovelace-yaml/system
            styles:
              icon:
                - color: >
                    [[[
                        if (location.pathname === "/lovelace-yaml/system")
                        return '#ffb300';
                    ]]]
          - type: custom:button-card
            template: icon_sticky_menu
            icon: mdi:map
            tap_action:
              action: navigate
              navigation_path: /lovelace-yaml/map
            styles:
              icon:
                - color: >
                    [[[
                        if (location.pathname === "/lovelace-yaml/map")
                        return '#ffb300';
                    ]]]
          - type: custom:button-card
            template: icon_sticky_menu
            icon: mdi:music-circle
            tap_action:
              action: navigate
              navigation_path: /d5369777_music_assistant_beta/ingress

          - type: custom:button-card
            template: icon_sticky_menu
            icon: mdi:chat
            tap_action:
              action: assist
              start_listening: false
