template:
  - sensor:
      - name: 'Hass Config Stargazers'
        state: '{{ states("sensor.hass_config_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'hass_config_stargazers'
      - name: 'Lunar Phase Card Stargazers'
        state: '{{ states("sensor.lunar_phase_card_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'lunar_phase_card_stargazers'
      - name: 'Lunar Phase Stargazers'
        state: '{{ states("sensor.lunar_phase_integration_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'lunar_phase_stargazers'
      - name: 'Vehicle Info Card Stargazers'
        state: '{{ states("sensor.repo_vehicle_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'vehicle_info_card_stargazers'
      - name: 'Vehicle Status Card Stargazers'
        state: '{{ states("sensor.vehicle_status_card_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'vehicle_status_card_stargazers'
      - name: 'Sidebar Organizer Stargazers'
        state: '{{ states("sensor.repo_sidebar_organizer_stars") }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'repo_sidebar_organizer_stargazers'
      ## TOTAL DOWNLOADS
      - name: 'Sidebar Organizer Total Downloads'
        state: '{{ states("sensor.sidebar_organizer_total_download") }}'
        icon: 'mdi:download'
        unit_of_measurement: 'downloads'
        unique_id: 'sidebar_organizer_total_downloads'
      - name: 'Sidebar Organizer Latest Release'
        state: '{{ states("sensor.sidebar_organizer_latest_release_download") }}'
        icon: 'mdi:download'
        unit_of_measurement: 'downloads'
        unique_id: 'sidebar_organizer_latest_release'
      - name: 'Vehicle Status Card Releases'
        state: >-
          {{ this.attributes.releases | list | count }}
        icon: 'mdi:download'
        unit_of_measurement: 'releases'
        unique_id: 'vehicle_status_card_releases'
        attributes:
          releases: >-
            {% set releases = state_attr('sensor.vehicle_status_card_total_app', 'releases').values()
              | selectattr('published_at', 'ne', none)
              | list %}
            {{ releases }}
