template:
  - sensor:
      - name: 'Hass Config Stargazers'
        state: '{{ states.sensor.hass_config_stars.state }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'hass_config_stargazers'
      - name: 'Lunar Phase Card Stargazers'
        state: '{{ states.sensor.lunar_phase_card_stars.state }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'lunar_phase_card_stargazers'
      - name: 'Lunar Phase Stargazers'
        state: '{{ states.sensor.lunar_phase_integration_stars.state }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'lunar_phase_stargazers'
      - name: 'Vehicle Info Card Stargazers'
        state: '{{ states.sensor.repo_vehicle_stars.state }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'vehicle_info_card_stargazers'
      - name: 'Vehicle Status Card Stargazers'
        state: '{{ states.sensor.vehicle_status_card_stars.state }}'
        icon: 'mdi:star'
        unit_of_measurement: 'stars'
        unique_id: 'vehicle_status_card_stargazers'
