##################################################
#                                               #
#                    FOOTER                     #
#                                               #
#################################################

# AHOJ!!!
- type: horizontal-stack
  view_layout:
    grid-area: footer
  cards:
    - type: custom:button-card
      name: >
        <ha-icon icon="mdi:reload"></ha-icon> Refresh
      tap_action:
        action: call-service
        service: browser_mod.sequence
        service_data:
          sequence:
            - service: shell_command.refresh_lovelace
            - service: browser_mod.javascript
              data:
                code: lovelace_reload()

      template:
        - footer

    - type: custom:button-card
      name: >
        <ha-icon icon="mdi:vacuum"></ha-icon> Vacuum
      tap_action: !include ../../shared/popup/footer/footer_vacuum.yaml
      triggers_update:
        - sensor.date
      variables:
        notify: >
          [[[
            let id = states['sensor.robot_vacuum_last_clean_end'];
            if (id) return (Date.now() - Date.parse(id.state)) > 6048e5;
          ]]]
      template:
        - footer

    - type: custom:button-card
      name: >
        <ha-icon icon="mdi:server"></ha-icon> System
      tap_action: !include ../../shared/popup/footer/footer_system.yaml
      template:
        - footer

    - type: custom:button-card
      name: >
        <ha-icon icon="ios:pc"></ha-icon> Server
      tap_action: !include ../../shared/popup/footer/footer_mbproserver.yaml
      template:
        - footer

    - type: custom:button-card
      entity: sensor.template_updates
      name: >
        <ha-icon icon="mdi:arrow-up-bold-circle-outline"></ha-icon> Updates
      tap_action: !include ../../shared/popup/footer/footer_updates.yaml
      variables:
        notify: >
          [[[
            return parseInt(entity?.state);
          ]]]
      template:
        - footer
    - type: custom:button-card
      name: >
        <ha-icon icon="mdi:chart-box"></ha-icon> Overview
      tap_action: !include ../../shared/popup/footer/footer_overview.yaml
      # variables:
      #   notify: >
      #     [[[
      #       let id = states['binary_sensor.galaxy_tab_a_plugged_in'];
      #       if (id) return id.state === 'off';
      #     ]]]
      template:
        - footer

    - type: custom:button-card
      name: >
        <ha-icon icon="mdi:router-wireless"></ha-icon> Network
      tap_action: !include ../../shared/popup/footer/footer_network.yaml
      triggers_update:
        - binary_sensor.template_unifi_alerts
        - update.unifi_status_update
      variables:
        notify: >
          [[[
            let id = this._config.triggers_update;
            if (id.every(e => states[e]))
                return states[id[0]].state === 'on'
                    ? `error`
                    : states[id[1]].state === 'on'
                      ? 1
                      : null;
          ]]]
      template:
        - footer
