---
kodi:
  tw-slate-900: '#0f172a'
  tw-gray-900: '#111827'
  tw-zinc-900: '#18181b'
  tw-neutral-900: '#171717'
  tw-stone-900: '#1c1917'
  tw-red-900: '#7f1d1d'
  tw-orange-900: '#7c2d12'
  tw-amber-900: '#78350f'
  tw-yellow-900: '#713f12'
  tw-lime-900: '#365314'
  tw-green-900: '#14532d'
  tw-emerald-900: '#064e3b'
  tw-teal-900: '#134e4a'
  tw-cyan-900: '#164e63'
  tw-sky-900: '#0c4a6e'
  tw-blue-900: '#1e3a8a'
  tw-indigo-900: '#312e81'
  tw-violet-900: '#4c1d95'
  tw-purple-900: '#581c87'
  tw-fuchsia-900: '#701a75'
  tw-pink-900: '#831843'
  tw-rose-900: '#8813'

  tw-slate-800: '#1e293b'
  tw-gray-800: '#1f2937'
  tw-zinc-800: '#27272a'
  tw-neutral-800: '#262626'
  tw-stone-800: '#292524'
  tw-red-800: '#991b1b'
  tw-orange-800: '#9a3412'
  tw-amber-800: '#92400e'
  tw-yellow-800: '#854d0e'
  tw-lime-800: '#3f6212'
  tw-green-800: '#166534'
  tw-emerald-800: '#065f46'
  tw-teal-800: '#115e59'
  tw-cyan-800: '#155e75'
  tw-sky-800: '#075985'
  tw-blue-800: '#1e40af'
  tw-indigo-800: '#3730a3'
  tw-violet-800: '#5b21b6'
  tw-purple-800: '#6b21a8'
  tw-fuchsia-800: '#86198f'
  tw-pink-800: '#9d174d'
  tw-rose-800: '#be123c'

  tw-slate: '#94a3b8'
  tw-gray: '#6b7280'
  tw-zinc: '#71717a'
  tw-neutral: '#737373'
  tw-stone: '#78716c'
  tw-red: '#f87171'
  tw-orange: '#fb923c'
  tw-amber: '#fbbf24'
  tw-yellow: '#facc15'
  tw-lime: '#a3e635'
  tw-green: '#4ade80'
  tw-emerald: '#10b981'
  tw-teal: '#2dd4bf'
  tw-cyan: '#22d3ee'
  tw-sky: '#38bdf8'
  tw-blue: '#60a5fa'
  tw-indigo: '#818cf8'
  tw-violet: '#a78bfa'
  tw-purple: '#c084fc'
  tw-fuchsia: '#e879f9'
  tw-pink: '#f472b6'
  tw-rose: '#fb7185'

  h1-font-size: 2.85rem
  h2-font-size: 2.25rem
  h3-font-size: 2rem
  h4-font-size: 1.5rem
  h5-font-size: 1.15rem
  h6-font-size: .7rem

  h1-font-weight: 100
  h2-font-weight: 100
  h3-font-weight: 100
  h4-font-weight: 600
  h5-font-weight: 400
  h6-font-weight: 400

  body-font-size: 1rem
  body-font-weight: normal
  body-line-height: normal
  card-title-font-size: 1.5rem
  card-title-font-weight: 600
  card-title-line-height: normal
  title-font-size: 3.5rem
  title-font-weight: 600
  title-line-height: normal
  subtitle-font-size: 1rem
  subtitle-font-weight: 600
  subtitle-line-height: normal
  small-font-size: 0.9rem

  body-font: 'var(--body-font-weight) var(--body-font-size)'
  card-title-font: 'var(--card-title-font-weight) var(--card-title-font-size)'
  h1-font: 'var(--h1-font-weight) var(--h1-font-size)'
  h2-font: 'var(--h2-font-weight) var(--h2-font-size)'
  h3-font: 'var(--h3-font-weight) var(--h3-font-size)'
  h4-font: 'var(--h4-font-weight) var(--h4-font-size)'
  h5-font: 'var(--h5-font-weight) var(--h5-font-size)'
  h6-font: 'var(--h6-font-weight) var(--h6-font-size)'
  # Progress bar conditional card
  progress-bar-color: '#e5a00d'
  progress-bar-background-color: rgba(0,0,0,0.33)
  progress-bar-height: 2%

  swiper-theme-color: '#ffffff'

  ha-card-header-font-size: var(--card-title-font-size)
  masonry-view-card-margin: 0
  card-mod-theme: 'kodi'
  card-mod-view-yaml: |
    .: |
      hui-view {
        background-size: cover !important;
        background-attachment: fixed !important;
        background-repeat: no-repeat !important;
      }
      @media screen and (max-width: 800px) {
        hui-view {
          background: none !important;
        }
      }
      #view {
        overflow: hidden;
      }
