Main Theme:
  modes:
    dark:
      primary-font-family: Poppins, Raleway, SF Pro Text, sans-serif, system-ui
      font-stack: Poppins, Raleway, SF Pro Text, sans-serif, system-ui
      display-font-stack: Poppins, Raleway, SF Pro Text, sans-serif, system-ui
      paper-font-common-base_-_font-family: var(--primary-font-family)
      paper-font-common-code_-_font-family: var(--primary-font-family)
      paper-font-body1_-_font-family: var(--primary-font-family)
      paper-font-subhead_-_font-family: var(--primary-font-family)
      paper-font-headline_-_font-family: var(--primary-font-family)
      paper-font-caption_-_font-family: var(--primary-font-family)
      paper-font-title_-_font-family: var(--primary-font-family)
      ha-card-header-font-family: var(--primary-font-family)
      mdc-typography-body1-font-family: var(--primary-font-family)
      mdc-typography-font-family: var(--primary-font-family)
      mdc-typography-button-font-family: var(--primary-font-family)
      paper-font-display1_-_font-family: var(--primary-font-family)
      paper-font-display2_-_font-family: var(--primary-font-family)
      paper-font-display3_-_font-family: var(--primary-font-family)
      paper-font-display4_-_font-family: var(--primary-font-family)

      error-color: '#db4437'
      disabled-text-color: '#bdbdbd'

      # Text
      text-color: '#ffffffb3'
      rgb-primary-text-color: '255, 255, 255'
      primary-text-color: 'var(--text-color)'
      text-primary-color: 'var(--text-color)'
      sidebar-text-color: 'var(--text-color)'
      pbs-button-color: 'var(--text-color)'
      pbs-button-rgb-color: 'var(--text-color)'
      pbs-button-rgb-state-color: 'var(--text-color)'
      pbs-button-rgb-default-color: 'var(--text-color)'
      rgb-state-default-color: 'var(--text-color)'
      pbs-button-rgb-fallback: 'var(--text-color)'
      secondary-text-color: '#BAC0C6'
      text-medium-light-color: '#A0A2A8'
      text-medium-color: '#80828A'

      # Text Fields an Dropdown
      # mdc-text-field-fill-color: 'var(--background-color-1)'
      # mdc-text-field-ink-color: 'var(--text-color)'
      # mdc-select-fill-color: 'var(--background-color-1)'
      # mdc-text-field-label-ink-color: 'var(--secondary-text-color)'
      # input-fill-color: 'var(--background-color-1)'
      # input-ink-color: 'var(--text-color)'
      # input-label-ink-color: 'var(--text-color)'
      # input-disabled-fill-color: 'var(--background-color-1)'
      # input-disabled-ink-color: 'var(--disabled-text-color)'
      # input-disabled-label-ink-color: 'var(--disabled-text-color)'
      # input-idle-line-color: 'var(--background-color-1)'
      # input-dropdown-icon-color: 'var(--secondary-text-color)'
      # input-hover-line-color: 'var(--primary-color)'
      # code-editor-background-color: '#222c40'
      # codemirror-property: 'var(--accent-color)'

      # Main Colors

      accent-color: '#2D9CDB'
      rgb-accent-color: '101,115,134'
      disabled-color: '#bdbdbd'

      primary-color: '#2D9CDB'
      rgb-primary-color: '45, 156, 219'
      # Card

      # Background
      background-color-1: '#000000'
      # primary-background-color: 'var(--background-color-1)'
      primary-background-color: '#000000'
      background-color-2: '#FF9800'
      rgb-header-background: '255, 255, 255'
      app-header-background-color: rgba(0,0,0,1)
      secondary-background-color: 'rgb(24,24,24)'

      # Card
      # masonry-view-card-margin: 0
      rgb-primary-background-color: '0,0,0'
      card-background-color: 'var(--ha-card-background)'
      ha-card-background: '#21252b'
      ha-card-box-shadow: 'none'
      # ha-card-border-radius: '28px'
      ha-card-border-style: 'none !important'
      ha-card-border-width: 0px
      ha-card-border-color: 'none !important'
      border-color: 'none'
      border-style: 'none !important'
      # # Icons
      paper-item-icon-color: 'var(--text-color)'
      paper-item-icon-active-color: 'var(--accent-color)'

      # Sidebar
      sidebar-background-color: 'var(--background-color-1)'
      sidebar-icon-color: '#9e9e9e80'
      scrollbar-thumb-color: '#303030'
      sidebar-selected-icon-color: 'var(--accent-color)'
      sidebar-selected-text-color: 'var(--text-color)'
      paper-listbox-background-color: 'var(--sidebar-background-color)'

      divider-color: 'var(--background-color-1)'
      # light-primary-color: 'var(--ha-card-background)'

      # # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--background-color-2)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'var(--background-color-2)'
      # Toggle:
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      mdc-theme-primary: 'var(--accent-color)'
      mdc-theme-secondary: 'var(--accent-color)'
      # Radio Button
      paper-radio-button-checked-color: 'var(--accent-color)'

      # # # Switch
      # switch-checked-button-color: var(--primary-color)
      # switch-checked-track-color: var(--primary-text-color)
      # switch-unchecked-button-color: var(--primary-text-color)
      # switch-unchecked-track-color: var(--primary-text-color)
      # mdc-radio-unchecked-color: var(--primary-text-color)

      # Tables
      table-row-background-color: 'var(--background-color-1)'
      table-row-alternative-background-color: 'var(--ha-card-background)'
      # Badges
      label-badge-background-color: 'var(--background-color-1)'
      label-badge-text-color: 'var(--text-primary-color)'
      label-badge-red: 'rgba(255,88,88,1)'
      label-badge-blue: 'rgba(26,137,245,1)'
      label-badge-green: 'rgba(0,202,139,1)'
      label-badge-yellow: 'rgba(222,176,107,1)'
      # POPUP MORE INFO
      dialog-box-shadow: var(--rgb-accent-color)
      dialog-backdrop-filter: blur(12px) brightness(0.3)
      popup-background-color: rgba(34,38,39,0.6)
      # popup-background-color: rgba(30,30,45, 0.8)
      # popup-border-width: 1px
      popup-border-radius: 1em
      popup-padding-x: 0px
      popup-padding-y: 0px
      popup-min-width: 20vw
      popup-max-width: 100vw
      tablet-popup-header-color: rgba(200, 218, 222, 0.05)
      tablet-popup-content-padding: 1.4em 2.2em 1.6em 1.5em
      tablet-popup-button-padding: 0.1em 2em 1.8em 2em
      tablet-popup-border-style: 1.5px solid rgba(0,0,0,0.2)
      tablet-popup-align-dialog: center
      tablet-popup-margin-top: 0px

      # dialog-box-shadow: 0px 2px 4px 0px rgba(0, 0 ,0 , .2)
      state-icon-color: '#9da0a2'
      state-icon-active-color: '#FF9800'
      state-active-color: '#b68349'
      # paper-slider-knob-start-color: '#a4abb1'
      # paper-toast-color: var(--primary-text-color)
      # paper-toast-background-color: '#1b1b1bf2'
      st-spacing: 0
  card-mod-theme: Main Theme

  card-mod-more-info-yaml: |
    $: |
      .mdc-dialog__surface {
        background-color: var(--popup-background-color);
        box-shadow: 0 0px 16px 4px rgba(var(--dialog-box-shadow), .15), 0 16px 64px 32px rgba(var(--dialog-box-shadow), .5);
      }

      .mdc-dialog__surface {
        background-color: var(--popup-background-color) !important;
        box-shadow: 0 0px 16px 4px rgba(var(--dialog-box-shadow), .15), 0 16px 64px 32px rgba(var(--dialog-box-shadow), .5) !important;
      }
      .mdc-deprecated-list {
        background-color: rgb(47, 55, 76) !important;
      }
    ha-header-bar$: |
      .mdc-top-app-bar {
        background: none !important;
      }
    ha-dialog-header$header: |
      div.header-bar {
        padding: 10px 17px 8px 17px;
      }
    ha-dialog$: |
      .mdc-dialog__surface {
        background-color: var(--popup-background-color) !important;
        box-shadow: 0 0px 16px 4px rgba(var(--dialog-box-shadow), .15), 0 16px 64px 32px rgba(var(--dialog-box-shadow), .5) !important;
      }


    .: |
      :host {
        --ha-card-border-width: 0 !important;
        --ha-card-border-radius: 0px !important;
        --ha-card-border-color: none !important;
        --bar-card-border-radius: 12px !important;
        --ha-card-box-shadow: none !important;
        --ha-card-background: none !important;
        --mdc-theme-surface: transparent;
      }

      ha-dialog > div.content > div.container {
        padding: 0 !important;
      }
      ha-dialog {
        --vertical-align-dialog: var(--tablet-popup-align-dialog) !important;
        --dialog-surface-margin-top: var(--tablet-popup-margin-top) !important;
      }
      @media (max-width: 800px), (max-height: 500px) {
        ha-dialog {
          --mdc-dialog-min-width: 100vw !important;
          --mdc-dialog-min-height: 100vh !important;
          --popup-border-radius: 0 !important;
        }
      }
      ha-dialog > div:focus {
        outline: none;
      }
