############################################
############################################
############################################

# BASE THEME

________________________________________Common Base (Do Not Use):
  modes:
    dark: &common-colors # grid-card-gap: 0.8vw
      vertical-stack-card-margin: 0
      state-icon-color: '#9da0a2'
      state-icon-active-color: '#3182b7'
      state-active-color: '#b68349'
      switch-checked-color: '#9e9e9e'
      switch-unchecked-button-color: '#9E9E9E'
      switch-unchecked-track-color: '#9E9E9E'
      paper-slider-knob-color: '#a4abb1'
      paper-slider-knob-start-color: '#a4abb1'
      paper-slider-pin-color: '#626a6f'
      paper-slider-active-color: '#626a6f'
      paper-slider-container-color: '#202020'
      paper-toast-color: var(--primary-text-color)
      paper-toast-background-color: '#1b1b1bf2'

      dialog-backdrop-filter: blur(12px) brightness(0.3)
      rgb-accent-color: '101,115,134'
      dialog-box-shadow: var(--rgb-accent-color)
      # dialog-box-shadow: 0px 2px 4px 0px rgba(0, 0 ,0 , .2)
      popup-background-color: rgba(34,38,39,0.6)
      popup-border-width: 1px
      popup-border-radius: 1em
      popup-padding-x: 0px
      popup-padding-y: 0px
      tablet-popup-header-color: rgba(200, 218, 222, 0.05)
      tablet-popup-content-padding: 1.4em 2.2em 1.6em 1.5em
      tablet-popup-button-padding: 0.1em 2em 1.8em 2em
      tablet-popup-border-style: 1.5px solid rgba(0,0,0,0.2)
      tablet-popup-align-dialog: center
      tablet-popup-margin-top: 0px

      #font
      primary-font-family: Poppins, Raleway, SF Pro Text, SF Pro Display, SF Mono, sans-serif, system-ui
      paper-font-common-base_-_font-family: var(--primary-font-family)
      paper-font-common-code_-_font-family: var(--primary-font-family)
      paper-font-body1_-_font-family: var(--primary-font-family)
      paper-font-subhead_-_font-family: var(--primary-font-family)
      paper-font-headline_-_font-family: var(--primary-font-family)
      paper-font-caption_-_font-family: var(--primary-font-family)
      paper-font-title_-_font-family: var(--primary-font-family)
      ha-card-header-font-family: Futura
      mdc-typography-body1-font-family: var(--primary-font-family)
      mdc-typography-font-family: var(--primary-font-family)
      #custom variables

      # custom-layout-card-padding: 2.2w #3.3vw or #3vw...#1.9...sidebar OK
      custom-layout-card-padding: 3vw
      grid-card-gap: 5%
      state-light-color: '#9da0a2'
      state-light-active-color: '#b68349'
      sidebar-time-font-size: 4.2vw
      sidebar-time-line-height: 4.3vw
      sidebar-font-size: 1vw
      sidebar-line-height: 2vw
      bar-card-color: '#303435'

      #button_card_templates
      button-card-font-size: 0.9vw
      button-card-state-size: 0.8vw
      button-card-movie-state-size: 0.8vw
      z-axis-adjustment: 0.05vw #tilt compensation
      button-card-font-weight: 500
      button-card-letter-spacing: 0
      button-card-border-radius: 10%
      chips-card-font-size: 0.8vw
      chips-card-state-size: 0.7vw
      chips-card-padding-v: 0.3vw
      chips-card-padding-h: 0.2vw
      chips-card-border-radius: 0.9vw
      footer-card-font-size: 1vw
      footer-card-icon-size: 1.2vw
      footer-card-padding-v: 0.5vw
      footer-card-padding-h: 1vw
      footer-card-border-radius: 0.65vw
      footer-notify-font-size: 0.9vw
      footer-notify-box-size: 1.8vw
      footer-notify-top: -0.9vw
      footer-notify-right: -1vw
      button-card-light-color-temp: hsl(204, 58%, 38%)
      # Progress bar conditional card
      progress-bar-color: '#e5a00d'
      progress-bar-background-color: rgba(0,0,0,0.33)
      progress-bar-height: 2%
      # Honeycomb buttons
      honeycomb-menu-background-color: 'linear-gradient(0deg, rgba(60,66,80,1) 0%, rgba(23,26,37,0.7) 42%, rgba(21,25,35,0.6) 100%)'
      honeycomb-menu-active-background-color: 'linear-gradient(45deg, #eee, #2d6ca0)'
      honeycomb-menu-icon-color: '#FFFFFF80'
      honeycomb-menu-icon-active-color: '#ffffffbd'
      honeycomb-menu-disabled: '#00000033'
      # Swiper
      swiper-theme-color: rgb(179, 179, 179)
      swiper-pagination-color: var(--swiper-theme-color)
      swiper-pagination-left: auto
      swiper-pagination-right: 8px
      swiper-pagination-bottom: 8px
      swiper-pagination-top: auto
      swiper-pagination-fraction-color: inherit
      swiper-pagination-progressbar-bg-color: rgba(0, 0, 0, 0.25)
      swiper-pagination-progressbar-size: 4px
      swiper-pagination-bullet-size: 8px
      swiper-pagination-bullet-width: 8px
      swiper-pagination-bullet-height: 8px
      swiper-pagination-bullet-inactive-color: '#000'
      swiper-pagination-bullet-inactive-opacity: 0.2
      swiper-pagination-bullet-opacity: 1
      swiper-pagination-bullet-horizontal-gap: 4px
      swiper-pagination-bullet-vertical-gap: 6px

############################################
############################################
############################################

________________________________________Common Base 3 (Do Not Use): &common-card-mods # Card Mod
  card-mod-view-yaml: &card-mod-view-yaml |
    .: |
      hui-view {
        background: var(--primary-background-color) !important;
      }
      #view {
        background-image: linear-gradient(180deg, rgb(0 0 0) 0%, rgba(23,26,37,1) 42%, rgba(21,25,35,1) 100%);
        overflow: hidden;
      }
      /* phone */
      @media screen and (max-width: 800px) {
        #view {
          background-image: linear-gradient(0deg, rgb(20 25 37) 0%, rgba(21,25,35,1) 72%, rgba(23,26,37,1) , rgb(0 0 0) 100%);
        }
      }
    #################################################
    #                                               #
    #              GRID CARD HEADINGS               #
    #                                               #
    #################################################
    grid-layout$:
      hui-grid-card:
        .: |
          hui-grid-card {
            padding-bottom: 1.5vw;
          }
          /* phone */
          @media screen and (max-width: 800px) {
            hui-grid-card {
              padding-bottom: 3vw;
            }
          }
        $: |
          /* default */
          h1 {
            font-size: 1.4vw !important;
            line-height: 0 !important;
            font-weight: 700 !important;
            font-family: raleway !important;
            letter-spacing: 0.05em !important;
            color: rgba(255, 255, 255, 0.7) !important;
            padding: 1vw 0 1.2vw 0.5vw !important;
            width: 100%;
          }
          /* secondmonitor */
          @media screen and (max-width: 1440px) {
            h1 {
              font-size: 2vw !important;
              padding-bottom: 1.7vw !important;
            }
          }
          /* phone */
          @media screen and (max-width: 800px) {
            h1 {
              font-size: 4vw !important;
              line-height: 100% !important;
              margin-inline: 1vw;
            }
          }
    #################################################
    #                                               #
    #               SWIPE CARD MARGIN               #
    #                                               #
    #################################################
        $swipe-card$:
          .: |
            .swiper-pagination {
              top: 95%;
            }
            .swiper-container-horizontal > .swiper-pagination-bullets {
              bottom: 0px !important;
            }
            .swiper-container {
              overflow-x: clip !important;
              margin: -1.5vw !important;
              padding: 1.5vw !important;
              margin-bottom: -2.5vw !important;
            }
            .swiper-pagination-bullet {
              background-color: rgba(255, 255, 255, .7) !important;
            }
            @media screen and (max-width: 800px) {
              .swiper-container {
                margin-bottom: 0vw !important;
              }
              .swiper-pagination {
                top: 92%;
              }
            }
          hui-horizontal-stack-card$:
            .: |
              hui-conditional-card {
                margin: 0 0.1vw 0 0 !important;
              }
          hui-horizontal-stack-card$hui-grid-card$swipe-card$:
            .: |
              .swiper-container {
                overflow-x: clip !important;
                margin: -1.5vw !important;
                padding: 1.5vw !important;
                margin-bottom: -1vw !important;
              }
              .swiper-pagination {
                right: 10% !important;
                top: 50% !important;
              }
              .swiper-pagination-bullet {
                background-color: rgba(255, 255, 255, .7) !important;
              }
              @media screen and (max-width: 800px) {
                .swiper-pagination-bullet {
                  width: 0.5em !important;
                  height: 0.5em !important;
                }
              }
    #################################################
    #                                               #
    #                    FOOTER                     #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:
      $: |
        #root {
          flex-wrap: wrap;
          justify-content: space-between;
          overflow: visible;
          margin-top: 0.5em;
        }
        @media only screen and (max-width: 1440px) {
          #root {
            justify-content: space-evenly;
          }
        }
        /* phone */
        @media screen and (max-width: 800px) {
          #root {
            margin-top: 1em;
            padding-bottom: 1em;
            justify-content: center;
          }
        }
    #################################################
    #                                               #
    #                   CHIPS                       #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:nth-child(2):
      $: |
        #root {
          justify-content: space-between;
          align-items: center;
        }
    grid-layout$hui-horizontal-stack-card:nth-child(3):
      $: |
        #root {
          justify-content: space-between;
          align-items: center;
        }
    #################################################
    #                                               #
    #                STICKY BOTTOM MENU             #
    #                                               #
    #################################################
    grid-layout$hui-vertical-stack-card$hui-vertical-stack-card:
      $: |
        #root {
          background-color: #1b1b1bf2 !important;
        }
    grid-layout$hui-horizontal-stack-card:nth-child(16):
      $: |
        #root {
          justify-content: space-evenly;
          align-items: center;
        }
        :host {
          position: fixed !important;
          bottom: 0;
          z-index: 1;
          justify-self: center;
          width: 100%;
          padding: 10px 0 20px;
          background-image: linear-gradient(0deg, #000000, transparent);
        }

  card-mod-card: &card-mod-card |
    .header .card-header {
      letter-spacing: 0.005em;
      font-size: 1.6em;
      font-weight: 500;
      line-height: initial;
      cursor: default;
    }
    .content .card-content {
      padding: var(--tablet-popup-content-padding);
    }
    /* * * * * * * * * * * * * * * * * *
    *                                 *
    *         CUSTOM BAR CARD         *
    *                                 *
    * * * * * * * * * * * * * * * * * */
    .type-custom-bar-card bar-card-name {
      padding-left: 0.25em;
      letter-spacing: normal;
    }
    .type-custom-bar-card bar-card-iconbar {
      padding-left: 0.23em;
    }
    .type-custom-bar-card bar-card-value {
      font-size: 0.9em;
      font-weight: 400;
      color: #e0e1e1;
      letter-spacing: 0.01em;
      text-shadow: none;
      margin-right: auto;
    }
    .type-custom-bar-card bar-card-backgroundbar {
      background: none;
    }
    .type-custom-bar-card bar-card-background {
      background: radial-gradient(circle, rgba(52, 57, 58, 0.1) 0%, rgba(17, 18, 18, 0.2) 75%);
      box-shadow: inset 0 0 25px #00000045;
      border-radius: 0.3em;
      overflow: hidden;
    }

library:
  card-mod-theme: 'library'
  <<: *common-card-mods

  ha-card-background: rgb(19,19,19)
  primary-background-color: rgb(0,0,0)
  title-font-size: 3.5rem
  title-font-weight: 600
  title-line-height: normal

  modes:
    dark:
      <<: *common-colors
