tablet:
  modes:
    dark:
      primary-font-family: Poppins, Raleway, SF Pro Text, SF Pro Display, SF Mono, sans-serif, system-ui
      paper-font-common-base_-_font-family: var(--primary-font-family)
      paper-font-common-code_-_font-family: var(--primary-font-family)
      paper-font-body1_-_font-family: var(--primary-font-family)
      paper-font-subhead_-_font-family: var(--primary-font-family)
      paper-font-headline_-_font-family: var(--primary-font-family)
      paper-font-caption_-_font-family: var(--primary-font-family)
      paper-font-title_-_font-family: var(--primary-font-family)
      ha-card-header-font-family: Futura
      mdc-typography-body1-font-family: var(--primary-font-family)
      mdc-typography-font-family: var(--primary-font-family)

      ha-card-background: none
      ha-card-box-shadow: none

      masonry-view-card-margin: 0
      # custom-layout-card-padding: 2.2w #3.3vw or #3vw...#1.9...sidebar OK
      custom-layout-card-padding: 3vw
      grid-card-gap: 5%

      state-icon-color: '#9da0a2'
      state-icon-active-color: '#3182b7'
      state-active-color: '#b68349'
      state-light-color: '#9da0a2'
      state-light-active-color: '#b68349'

      #button_card_templates
      button-card-border-radius: 10%
      button-card-font-size: 0.9vw
      button-card-font-weight: 500
      button-card-letter-spacing: 0
      button-card-light-color-temp: hsl(204, 58%, 38%)
      button-card-movie-state-size: 0.8vw
      button-card-state-size: 0.8vw
      chips-card-border-radius: 0.9vw
      chips-card-font-size: 0.8vw
      chips-card-padding-h: 0.2vw
      chips-card-padding-v: 0.3vw
      chips-card-state-size: 0.7vw
      footer-card-border-radius: 0.65vw
      footer-card-font-size: 1vw
      footer-card-icon-size: 1.2vw
      footer-card-padding-h: 1vw
      footer-card-padding-v: 0.5vw
      footer-notify-box-size: 1.8vw
      footer-notify-font-size: 0.9vw
      footer-notify-right: -1vw
      footer-notify-top: -0.9vw
      sidebar-time-font-size: 4.2vw
      sidebar-time-line-height: 4.3vw
      sidebar-font-size: 1vw
      sidebar-line-height: 2vw
      bar-card-color: '#303435'
      z-axis-adjustment: 0.05vw #tilt compensation

      # Progress bar conditional card
      progress-bar-color: '#e5a00d'
      progress-bar-background-color: rgba(0,0,0,0.33)
      progress-bar-height: 0.5rem

      # Honeycomb buttons
      honeycomb-menu-active-background-color: 'linear-gradient(45deg, #eee, #2d6ca0)'
      honeycomb-menu-background-color: 'linear-gradient(0deg, rgba(60,66,80,1) 0%, rgba(23,26,37,0.7) 42%, rgba(21,25,35,0.6) 100%)'
      honeycomb-menu-disabled: '#00000033'
      honeycomb-menu-icon-active-color: '#ffffffbd'
      honeycomb-menu-icon-color: '#FFFFFF80'

      # Swiper
      swiper-pagination-bottom: 8px
      swiper-pagination-bullet-height: 8px
      swiper-pagination-bullet-horizontal-gap: 4px
      swiper-pagination-bullet-inactive-color: '#000'
      swiper-pagination-bullet-inactive-opacity: 0.2
      swiper-pagination-bullet-opacity: 1
      swiper-pagination-bullet-size: 8px
      swiper-pagination-bullet-vertical-gap: 6px
      swiper-pagination-bullet-width: 8px
      swiper-pagination-color: var(--swiper-theme-color)
      swiper-pagination-fraction-color: inherit
      swiper-pagination-left: auto
      swiper-pagination-progressbar-bg-color: rgba(0, 0, 0, 0.25)
      swiper-pagination-progressbar-size: 4px
      swiper-pagination-right: 8px
      swiper-pagination-top: auto
      swiper-theme-color: rgb(179, 179, 179)
      tablet-popup-content-padding: 1.4em 2.2em 1.6em 1.5em

  card-mod-theme: 'tablet'

  card-mod-view-yaml: |
    .: |
      hui-view {
        background: none !important;
      }
      #view {
        background-image: linear-gradient(180deg, rgb(0 0 0) 0%, rgba(23,26,37,1) 42%, rgba(21,25,35,1) 100%);
        overflow: hidden;
      }
      /* phone */
      @media screen and (max-width: 800px) {
        #view {
          background-image: linear-gradient(0deg, rgb(20 25 37) 0%, rgba(21,25,35,1) 72%, rgba(23,26,37,1) , rgb(0 0 0) 100%);
        }
      }
    #################################################
    #                                               #
    #              GRID CARD HEADINGS               #
    #                                               #
    #################################################
    grid-layout$:
      hui-grid-card:
        .: |
          hui-grid-card {
            padding-bottom: 1.5vw;
          }
          /* phone */
          @media screen and (max-width: 800px) {
            hui-grid-card {
              padding-bottom: 3vw;
            }
          }
        $: |
          /* default */
          h1 {
            font-size: 1.4vw !important;
            line-height: 0 !important;
            font-weight: 700 !important;
            font-family: Raleway !important;
            letter-spacing: 0.05em !important;
            color: rgba(255, 255, 255, 0.7) !important;
            padding: 1vw 0 1.2vw 0.5vw !important;
            width: 100%;
          }
          /* secondmonitor */
          @media screen and (max-width: 1440px) {
            h1 {
              font-size: 2vw !important;
              padding-bottom: 1.7vw !important;
            }
          }
          /* phone */
          @media screen and (max-width: 800px) {
            h1 {
              font-size: 4vw !important;
              line-height: 100% !important;
              margin-inline: 1vw;
            }
          }
    #################################################
    #                                               #
    #               SWIPE CARD MARGIN               #
    #                                               #
    #################################################
        $swipe-card$:
          .: |
            .swiper-pagination {
              top: 95%;
            }
            .swiper-container-horizontal > .swiper-pagination-bullets {
              bottom: 0px !important;
            }
            .swiper-container {
              margin: -1.5vw !important;
              padding: 1.5vw !important;
              margin-bottom: -2.5vw !important;
            }
            .swiper-pagination-bullet {
              background-color: rgba(255, 255, 255, .7) !important;
              transition: all 0.3s ease-in-out !important;
            }
            .swiper-pagination-bullet-active {
              width: 18px !important;
              border-radius: 1rem !important;
            @media screen and (max-width: 800px) {
              .swiper-container {
                margin-bottom: 0vw !important;
              }
              .swiper-pagination {
                top: 92%;
              }
            }
          hui-horizontal-stack-card$:
            .: |
              hui-conditional-card {
                margin: 0 0.1vw 0 0 !important;
              }
          hui-horizontal-stack-card$hui-grid-card$swipe-card$:
            .: |
              .swiper-container {
                margin: -1.5vw !important;
                padding: 1.5vw !important;
                margin-bottom: -1vw !important;
              }
              .swiper-pagination {
                right: 10% !important;
                top: 50% !important;
              }
              .swiper-pagination-bullet {
                background-color: rgba(255, 255, 255, .7) !important;
              }
              @media screen and (max-width: 800px) {
                .swiper-pagination-bullet {
                  width: 0.5em !important;
                  height: 0.5em !important;
                }
              }
    #################################################
    #                                               #
    #                    FOOTER                     #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:
      $: |
        #root {
          flex-wrap: wrap;
          justify-content: space-between;
          overflow: visible;
          margin-top: 0.5em;
        }
        @media only screen and (max-width: 1440px) {
          #root {
            justify-content: space-evenly;
          }
        }
        /* phone */
        @media screen and (max-width: 800px) {
          #root {
            margin-top: 1em;
            padding-bottom: 1em;
            justify-content: center;
          }
        }
    #################################################
    #                                               #
    #                   CHIPS                       #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:nth-child(2):
      $: |
        #root {
          justify-content: space-between;
          align-items: center;
        }
    grid-layout$hui-horizontal-stack-card:nth-child(3):
      $: |
        #root {
          justify-content: space-between;
          align-items: center;
        }

  card-mod-card: |
    .header .card-header {
      letter-spacing: 0.005em;
      font-size: 1.6em;
      font-weight: 500;
      line-height: initial;
      cursor: default;
    }
    .content .card-content {
      padding: var(--tablet-popup-content-padding) !important;
    }

    /* * * * * * * * * * * * * * * * * *
    *                                 *
    *         CUSTOM BAR CARD         *
    *                                 *
    * * * * * * * * * * * * * * * * * */
    .type-custom-bar-card bar-card-name {
      padding-left: 0.25em;
      letter-spacing: normal;
    }
    .type-custom-bar-card bar-card-iconbar {
      padding-left: 0.23em;
    }
    .type-custom-bar-card bar-card-value {
      font-size: 0.9em;
      font-weight: 400;
      color: #e0e1e1;
      letter-spacing: 0.01em;
      text-shadow: none;
      margin-right: auto;
    }
    .type-custom-bar-card bar-card-backgroundbar {
      background: none;
    }
    .type-custom-bar-card bar-card-background {
      background: radial-gradient(circle, rgba(52, 57, 58, 0.1) 0%, rgba(17, 18, 18, 0.2) 75%);
      box-shadow: inset 0 0 25px #00000045;
      border-radius: 0.3em;
      overflow: hidden;
    }
