tablet:
  modes: { dark: { .: . } }

  tablet-primary-color: '#00acc1'
  primary-font-family: Poppins, Raleway, SF Pro Text, SF Pro Display, SF Mono, sans-serif, system-ui
  paper-font-common-base_-_font-family: var(--primary-font-family)
  paper-font-common-code_-_font-family: var(--primary-font-family)
  paper-font-body1_-_font-family: var(--primary-font-family)
  paper-font-subhead_-_font-family: var(--primary-font-family)
  paper-font-headline_-_font-family: var(--primary-font-family)
  paper-font-caption_-_font-family: var(--primary-font-family)
  paper-font-title_-_font-family: var(--primary-font-family)
  ha-card-header-font-family: Futura
  mdc-typography-body1-font-family: var(--primary-font-family)
  mdc-typography-font-family: var(--primary-font-family)
  app-header-background-color: rgba(0,0,0,1)
  ha-card-background: none
  ha-card-box-shadow: none

  masonry-view-card-margin: 0
  # custom-layout-card-padding: 2.2w #3.3vw or #3vw...#1.9...sidebar OK
  custom-layout-card-padding: 3vw
  grid-card-gap: 5%

  state-icon-color: '#9da0a2'
  state-icon-active-color: '#3182b7'
  state-active-color: '#b68349'
  state-light-color: '#9da0a2'
  state-light-active-color: '#b68349'

  #button_card_templates
  button-card-border-radius: 10%
  button-card-font-size: 0.9vw
  button-card-font-weight: 500
  button-card-letter-spacing: 0
  button-card-light-color-temp: hsl(204, 58%, 38%)
  button-card-movie-state-size: 0.8vw
  button-card-state-size: 0.8vw
  chips-card-border-radius: 0.9vw
  chips-card-font-size: 0.8vw
  chips-card-padding-h: 0.2vw
  chips-card-padding-v: 0.3vw
  chips-card-state-size: 0.7vw
  footer-card-border-radius: 0.65vw
  footer-card-font-size: 1vw
  footer-card-icon-size: 1.2vw
  footer-card-padding-h: 1vw
  footer-card-padding-v: 0.5vw
  footer-notify-box-size: 1.8vw
  footer-notify-font-size: 0.9vw
  footer-notify-right: -1vw
  footer-notify-top: -0.9vw
  sidebar-time-font-size: 4.2vw
  sidebar-time-line-height: 4.3vw
  sidebar-font-size: 1vw
  sidebar-line-height: 2vw
  bar-card-color: '#303435'
  z-axis-adjustment: 0.05vw #tilt compensation

  # Progress bar conditional card
  progress-bar-color: 'var(--tablet-primary-color)'
  progress-bar-background-color: rgba(0,0,0,0.33)
  progress-bar-height: 0.5rem

  # Honeycomb buttons
  honeycomb-menu-active-background-color: 'linear-gradient(45deg, #eee, #2d6ca0)'
  honeycomb-menu-background-color: 'linear-gradient(0deg, rgba(60,66,80,1) 0%, rgba(23,26,37,0.7) 42%, rgba(21,25,35,0.6) 100%)'
  honeycomb-menu-disabled: '#00000033'
  honeycomb-menu-icon-active-color: '#ffffffbd'
  honeycomb-menu-icon-color: '#FFFFFF80'

  tablet-popup-content-padding: 1.4em 2.2em 1.6em 1.5em

  # Swiper
  swiper-pagination-bottom: 8px
  swiper-pagination-bullet-height: 8px
  swiper-pagination-bullet-horizontal-gap: 4px
  swiper-pagination-bullet-inactive-color: '#000'
  swiper-pagination-bullet-inactive-opacity: 0.2
  swiper-pagination-bullet-opacity: 1
  swiper-pagination-bullet-size: 8px
  swiper-pagination-bullet-vertical-gap: 6px
  swiper-pagination-bullet-width: 8px
  swiper-pagination-color: var(--swiper-theme-color)
  swiper-pagination-fraction-color: inherit
  swiper-pagination-left: auto
  swiper-pagination-progressbar-bg-color: rgba(0, 0, 0, 0.25)
  swiper-pagination-progressbar-size: 4px
  swiper-pagination-right: 8px
  swiper-pagination-top: auto
  swiper-theme-color: rgb(179, 179, 179)

  swiper-scrollbar-border-radius: 10px
  swiper-scrollbar-top: auto
  swiper-scrollbar-bottom: 4px
  swiper-scrollbar-left: auto
  swiper-scrollbar-right: 4px
  swiper-scrollbar-sides-offset: 1%
  swiper-scrollbar-bg-color: rgba(0, 0, 0, 0.25)
  swiper-scrollbar-drag-bg-color: rgb(179, 179, 179)
  swiper-scrollbar-size: 4px

  card-mod-theme: tablet

  card-mod-view-yaml: |
    .: |
      :host {
        # --app-header-background-color: rgba(0,0,0,1);
        --app-header-background-color: rgba(22, 24, 29, 1);
      }

      #view {
        background-image: linear-gradient(180deg, rgba(22, 24, 29, 1) 0%, rgba(23, 26, 37, 1) 42%, rgba(22, 24, 29, 1) 100%) !important;
        overflow: hidden !important;
      }
      /* phone */
      @media screen and (max-width: 800px) {
        #view {
          background-image: linear-gradient(0deg, rgb(20 25 37) 0%, rgba(21,25,35,1) 72%, rgba(23,26,37,1) , rgb(0 0 0) 100%);
        }
      }
    #################################################
    #                                               #
    #              GRID CARD HEADINGS               #
    #                                               #
    #################################################
    grid-layout:
      $: |
        #root {
          min-height: 100%;
        }
      $hui-grid-card:
        $: |
          /* default */
          h1 {
            font-size: 1.4vw !important;
            font-weight: 700 !important;
            font-family: Raleway !important;
            letter-spacing: 0.05em !important;
            color: rgba(255, 255, 255, 0.7) !important;
            padding: 0 0 1rem 0.2vw !important;
            width: 100%;
            line-height: 100% !important;
          }
          /* secondmonitor */
          @media screen and (max-width: 1440px) {
            h1 {
              font-size: 2vw !important;
              padding-bottom: 1.7vw !important;
            }
          }
          /* phone */
          @media screen and (max-width: 800px) {
            h1 {
              padding-top: 1rem !important;
              font-size: 4vw !important;
              line-height: 100% !important;
            }
          }

    #################################################
    #                                               #
    #               SWIPE CARD MARGIN               #
    #                                               #
    #################################################
        $swipe-card$:
          .: |
            .swiper-pagination {
              top: 95%;
            }
            .swiper-container-horizontal > .swiper-pagination-bullets {
              bottom: 0px !important;
            }
            .swiper-container {
              overflow-x: clip !important;
              margin: -1rem !important;
              padding: 1rem !important;
              //margin-bottom: -2.5vw !important;
              overflow-y: visible !important;
            }
            .swiper-pagination-bullet {
              background-color: rgba(255, 255, 255, .7) !important;
              transition: all 0.3s ease-in-out !important;
            }
            .swiper-pagination-bullet-active {
              width: 18px !important;
              border-radius: 1rem !important;
            @media screen and (max-width: 800px) {
              .swiper-container {
                overflow-x: clip !important;
                margin-bottom: 0vw !important;
              }
              .swiper-pagination {
                top: 92%;
              }
            }
          hui-horizontal-stack-card$:
            .: |
              hui-conditional-card {
                margin: 0 0.1vw 0 0 !important;
              }
          hui-horizontal-stack-card$hui-grid-card$swipe-card$:
            .: |
              .swiper-container {
                overflow-x: clip !important;
                margin: -1.5vw !important;
                padding: 1.5vw !important;
                margin-bottom: -1vw !important;
                overflow-y: visible !important;
              }
              .swiper-pagination {
                right: 10% !important;
                top: 50% !important;
              }
              .swiper-pagination-bullet {
                background-color: rgba(255, 255, 255, .7) !important;
              }
              @media screen and (max-width: 800px) {
                .swiper-pagination-bullet {
                  width: 0.5em !important;
                  height: 0.5em !important;
                }
              }


    #################################################
    #                                               #
    #                    CHIPS                      #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:
      $: |
        #root {
          flex-wrap: wrap;
          justify-content: space-between;
          place-items: center;
          //margin-top: 0.5em;
        }

    #################################################
    #                                               #
    #                   FOOTER                      #
    #                                               #
    #################################################
    grid-layout$hui-horizontal-stack-card:last-child:
      $: |
        #root {
          justify-content: space-between;
          align-items: center;
          height: 100%;
          flex-wrap: wrap;
        }
        @media only screen and (max-width: 1440px) {
          #root {
            justify-content: space-evenly;
          }
        }
        @media only screen and (max-width: 800px) {
          #root {
            justify-content: space-evenly;
            //gap: 1.5rem !important
          }
        }
    #################################################
    #                                               #
    #            HISTORY GRAPH                      #
    #                                               #
    #################################################
    grid-layout$history-explorer-card>ha-card:
      $: |
        h1 {
          line-height: unset !important;
        }

  card-mod-card: |
    .header .card-header {
      letter-spacing: 0.005em;
      font-size: 1.6em;
      font-weight: 500;
      line-height: initial;
      cursor: default;
      padding: 0 !important;
    }
    .content .card-content {
      padding: var(--tablet-popup-content-padding) !important;
    }

    ha-card.addon.type-entities {
      justify-content: flex-start !important;
    }

    .addon .card-content {
      padding: 0 !important;
      align-content: flex-start;
      --total-rows: 5;
    }

    @media screen and (max-width: 1710px) {
      .addon .card-header {
        padding: 0 !important;
        line-height: unset !important;
      }
      .addon .card-content {
        max-height: calc(calc(128px + 7px) * var(--total-rows, 5));
        overflow-y: auto;
        overflow-x: hidden;
        margin-top: 1rem !important;
      }
    }
    @media screen and (max-width: 800px) {
      .addon .card-content {
        --total-rows: 3;
      }
    }
    .stargazer .card-header {
      padding: 0 1rem !important;
      line-height: normal !important;
    }

    .stargazer .card-content {
      max-height: 435px;
      overflow-y: auto;
      margin-top: 1rem;
    }

    @media screen and (max-width: 800px) {
      .stargazer .card-content {
        padding: 0 !important;
      }
    }

    /* * * * * * * * * * * * * * * * * *
    *                                 *
    *         CUSTOM BAR CARD         *
    *                                 *
    * * * * * * * * * * * * * * * * * */
    .type-custom-bar-card bar-card-name {
      padding-left: 0.25em;
      letter-spacing: normal;
    }
    .type-custom-bar-card bar-card-iconbar {
      padding-left: 0.23em;
    }
    .type-custom-bar-card bar-card-value {
      font-size: 0.9em;
      font-weight: 400;
      color: #e0e1e1;
      letter-spacing: 0.01em;
      text-shadow: none;
      margin-right: auto;
    }
    .type-custom-bar-card bar-card-backgroundbar {
      background: none;
    }
    .type-custom-bar-card bar-card-background {
      background: radial-gradient(circle, rgba(52, 57, 58, 0.1) 0%, rgba(17, 18, 18, 0.2) 75%);
      box-shadow: inset 0 0 25px #00000045;
      border-radius: 0.3em;
      overflow: hidden;
    }

    @media screen and (min-width: 1720px) {
      .type-custom-history-explorer-card div#graphlist {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 100%;
        gap: 1rem !important;
      }
      .type-custom-history-explorer-card div#graphlist > br {
        display: none !important;
      }
    }
