# LOVELACE
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:home-circle
      show_in_sidebar: true
      filename: dashboards/ui-lovelace-main.yaml
    # Dashboard for Smart Displays
    ui-smart-displays:
      show_in_sidebar: true
      icon: mdi:devices
      title: For Smart Displays
      require_admin: false
      mode: yaml
      filename: ui/ui-smartdisplays.yaml

    ui-smart-displays-bedroom:
      show_in_sidebar: true
      icon: mdi:devices
      title: For Smart Displays (Bedroom)
      require_admin: false
      mode: yaml
      filename: ui/ui-smartdisplays-bedroom.yaml

    ui-smart-displays-minimal:
      show_in_sidebar: true
      icon: mdi:devices
      title: For Smart Displays (Minimal)
      require_admin: false
      mode: yaml
      filename: ui/ui-smartdisplays-minimal.yaml
