#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#
#
#- from github.com/ngocjohn/hass-config
#
########################################
#   HOME ASSISTANT CORE                #
########################################
rest:
  - resource: https://api.github.com/repos/home-assistant/core/releases/latest
    sensor:
      name: hass_release_notes
      unique_id: 'ee81059a-b51f-44cc-9a36-26c938e48c73'
      value_template: >
        {{ value_json.name }}
      json_attributes:
        - body
        - html_url
    scan_interval: 21600
  - resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
    sensor:
      name: hass_release_notes_beta
      unique_id: '4f92b2cc-2ee1-4d67-beda-713795139f29'
      value_template: >
        {{ value_json[0].name }}
      json_attributes:
        - body
        - html_url
    scan_interval: 21600
template:
  - sensor:
      # SENSOR - HASS CORE NEXT RELEASE
      - unique_id: hass_next_release
        state: >
          {% set start_time = state_attr('calendar.home_assistant_devs', 'start_time') %}
          {{ (as_timestamp(start_time, default=0) + 60*60*20.5) | timestamp_local(default) }}
        name: >
          {% set release = state_attr('calendar.home_assistant_devs','message') %}
          {% if release == 'Home Assistant Core Beta Release' %}
            Next beta
          {% elif release == 'Home Assistant Core Release' %}
            Next release
          {% else %}
            {{ release }}
          {% endif %}
        attributes:
          icon: mdi:dev-to
          device_class: timestamp
      - unique_id: hass_update_available
        name: 'Hassio Updates Available'
        state: >
          {{ this.attributes.update_entities }}
        attributes:
          home_assistant: >-
            {% set installed = states('sensor.current_version') %}
            {% set latest = states('sensor.home_assistant_versions') %}
            {{ iif(version(latest) > version(installed) and '.' in installed and '.' in latest, 1, 0) }}
          update_entities: >-
            {% set mqtt_ignores = integration_entities('mqtt')  | select('search', 'update.') | list %}
            {{ states.update | selectattr('state','eq','on')  |  rejectattr('entity_id', 'in', mqtt_ignores ) | list | count }}
          update_entities_list: >-
            {% set mqtt_ignores = integration_entities('mqtt')  | select('search', 'update.') | list %}
            {{ states.update | selectattr('state','eq','on')  |  rejectattr('entity_id', 'in', mqtt_ignores ) | map(attribute='entity_id') | list }}

      # SENSOR - DOMAIN COUNTER
      # - unique_id: domain_counter
      #   name: 'Domain Counter'
      #   state: >
      #     {{ states | count }}
      #   attributes:
      #     automation: >
      #       {{ states.automation | count }}
      #     binary_sensor: >
      #       {{ states.binary_sensor | count }}
      #     device_tracker: >
      #       {{ states.device_tracker | count }}
      #     light: >
      #       {{ states.light | count }}
      #     media_player: >
      #       {{ states.media_player | count }}
      #     sensor: >
      #       {{ states.sensor | count }}
      #     switch: >
      #       {{ states.switch | count }}
      #     other: >
      #       {% set exclude = this.attributes | list %}
      #       {{ states | rejectattr('domain', 'in', exclude) | list | count }}

      - name: Hassio addons use
        unique_id: 'c9d0b358-302b-4845-b3b7-606a54c0e1bd'
        state: >-
          {% if has_value('sensor.ha_system_cpu_usage') and has_value('sensor.ha_system_memory_usage') %}
          {%- set memory = states.sensor.ha_system_memory_usage.state | float -%}
          {%- set cpu = states.sensor.ha_system_cpu_usage.state | float -%}
            MEMORY: {{memory}}% | CPU: {{cpu}}%
          {%- endif %}
        icon: mdi:home-assistant
        attributes:
          addons: >
            {% from 'device_tools.jinja' import get_device_attr, get_addon_entities %}
            {%- set data = namespace(active=[]) -%}
            {%- set dev_inactive = namespace(offline=[]) -%}
            {%- set devices = label_devices('addons') -%}

            {%- for dev in devices -%}
              {%- set dev_attr = get_device_attr(dev) | from_json  -%}
              {%- set dev_entities = get_addon_entities(dev) | from_json -%}
              {%- set conf_url = device_attr(dev, 'configuration_url') | replace('homeassistant:/', '') -%}
              {%- set path = "/config/app/" + dev_attr.slug -%}
              {%- set addon_data = {
                'dev_id': dev,
                'name': dev_attr.name,
                'slug_name': dev_attr.slug,
                'conf_url': conf_url,
                'running_ent': dev_entities.get('running'),
                'cpu_ent': dev_entities.get('cpu_percent'),
                'memory_ent': dev_entities.get('memory_percent'),
                'update_ent': dev_entities.get('update'),
                'version_ent': dev_entities.get('version'),
                'path': path
              } -%}

              {%- if is_state(dev_entities.running, 'on') -%}
                {%- set data.active = data.active + [addon_data] -%}
              {%- else -%}
                {%- set dev_inactive.offline = dev_inactive.offline + [addon_data] -%}
              {%- endif -%}
            {%- endfor -%}

            {{ {'active':  data.active, 'inactive':  dev_inactive.offline}  }}

command_line:
  - sensor:
      unique_id: hacs_installed
      name: HACS installed
      command: |-
        python3 << EOF
        import os, json
        installed = {"repositories": []}
        PATH = "/config/.storage/hacs.repositories"
        with open(PATH, "r", encoding="UTF-8") as file:
            data = json.load(file)["data"]
            for i in data:
                if "installed" in data[i]:
                    installed["repositories"] += [data[i]["full_name"]]
            file.close()
        print(json.dumps(installed))
        EOF
      value_template: >
        {{ value_json.repositories | count }}
      json_attributes:
        - repositories
      scan_interval: 86400

########################################

sensor:
  - platform: websocket_api
