#-
#  _       _                       _   _
# (_)_ __ | |_ ___  __ _ _ __ __ _| |_(_) ___  _ __  ___
# | | '_ \| __/ _ \/ _` | '__/ _` | __| |/ _ \| '_ \/ __|
# | | | | | ||  __/ (_| | | | (_| | |_| | (_) | | | \__ \
# |_|_| |_|\__\___|\__, |_|  \__,_|\__|_|\___/|_| |_|___/
#                  |___/
#
#- from github.com/ngocjohn/hass-config
#
# roidmi.vacuum.v60 (Roidmi EVE Plus)
xiaomi_miot:
  username: !secret vacuum_username
  password: !secret vacuum_password
  server_country: de
  device_customizes:
    roidmi.vacuum.v60:
      exclude_miot_services: null
      interval_seconds: 10
      chunk_coordinators:
        - interval: 10
          props: 'status,mode,sweep_type,charging_state'
          notify: true
        - interval: 10
          props: 'fault,mop,water_level'
        - interval: 10
          props: >-
            double_clean,edge_sweep,battery_level,clean_area,clean_time,work_station_freq
        - interval: 60
          props: 'auto_boost,led_switch,lidar_collision,station_key,station_led,volume,mute'
        - interval: 151
          props: 'total_clean_time,total_clean_areas,clean_counts,path_type'
        - interval: 600
          props: 'filter_l*,brush_l*'
        - interval: 610
          props: 'custom.uid,timing,forbid_mode,current_audio,map_memory,use_auto_area'
    careli.fryer.maf02:
      check_lan: false
      exclude_miot_services: null
favicon:
  tile: Neklanka
  icon_path: /local/favicons/
