#-
#  _                _
# | | _____   _____| | __ _  ___ ___
# | |/ _ \ \ / / _ \ |/ _` |/ __/ _ \
# | | (_) \ V /  __/ | (_| | (_|  __/
# |_|\___/ \_/ \___|_|\__,_|\___\___|
#
#
#- from github.com/ngocjohn/hass-config
#
# LOVELACE
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:home-circle
      show_in_sidebar: true
      filename: dashboards/ui-lovelace-main.yaml

    ui-lovelace-test:
      mode: yaml
      title: Test
      icon: mdi:test-tube
      show_in_sidebar: true
      filename: dashboards/ui-lovelace-test.yaml
