template:
  - binary_sensor:
      - name: 'MacbookPro'
        unique_id: '1bd2146a-71b3-4b5b-b86a-14c732042731'
        device_class: running
        icon: ios:desktopcomputer
        state: "{{ is_state_attr('binary_sensor.mbproserver_active', 'Sleeping', false ) }}"
