#
#     ______            _____                        __  _
#    / ____/___  ____  / __(_)___ ___  ___________ _/ /_(_)___  ____
#   / /   / __ \/ __ \/ /_/ / __ `/ / / / ___/ __ `/ __/ / __ \/ __ \
#  / /___/ /_/ / / / / __/ / /_/ / /_/ / /  / /_/ / /_/ / /_/ / / / /
#  \____/\____/_/ /_/_/ /_/\__, /\__,_/_/   \__,_/\__/_/\____/_/ /_/
#                         /____/
homeassistant:
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  external_url: !secret external_url
  packages: !include_dir_named packages
  time_zone: 'Europe/Prague'
  unit_system: 'metric'
  temperature_unit: 'C'
  country: 'CZ'
  allowlist_external_dirs:
    - /config
  media_dirs:
    movies: /media/movies
    media: /media
default_config:
# FRONT - END
frontend:
  javascript_version: latest
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

# HTTP
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
# STT
stt:
  - platform: google_cloud_stt
    key_file: google_stt.json
    model: command_and_search
# INCLUDES
automation ui: !include automations.yaml
script: !include scripts.yaml
api:
