# Google Assistant Configuration
# Managed entities are in google_assistant_entities.yaml

project_id: hamyhome
service_account: !include SERVICE_ACCOUNT.json
report_state: true
expose_by_default: false
entity_config: !include google_assistant_entities.yaml
