# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

########################################
#   HASS SYSTEM SECRETS               #
########################################

homeassistant_latitude: '***REDACTED***'
homeassistant_longitude: '***REDACTED***'
homeassistant_elevation: '***REDACTED***'
external_url: '***REDACTED***'

mariadb_username: '***REDACTED***'
mariadb_pass: '***REDACTED***'
mariadb_url: '***REDACTED***'

refresh_lovelace: '***REDACTED***'

  # API TOKEN
ms_api: '***REDACTED***'
google_api: '***REDACTED***'
tmdb_api: '***REDACTED***'
radarr_api: '***REDACTED***'

  # Chat GPT #
gpt_cookies: '***REDACTED***'
mindsdb_email: '***REDACTED***'
mindsdb_password: '***REDACTED***'
pinecone_key: '***REDACTED***'
openai_key: '***REDACTED***'

telegram_api: '***REDACTED***'

  # DOCKER
pidocker_restart: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/pidocker ***REDACTED*** "sudo shutdown -r now"
pause_watchtower: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/pidocker ***REDACTED*** "docker pause watchtower"
unpause_watchtower: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/pidocker ***REDACTED*** "docker unpause watchtower"
purge_dockerlog: ssh -q -o StrictHostKeyChecking=no -i /config/.ssh/pidocker ***REDACTED*** "sudo sh -c 'truncate -s 0 /var/lib/docker/containers/**/*-json.log'"

commit_updates: python ***REDACTED***

  # MACBOOK AIR
sleep_mac: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'osascript -e "tell app \"System Events\" to sleep" 2>/dev/null'
wake_mac: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'caffeinate -u -t 3600'
login_mac: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'osascript -e "tell app \"System Events\" to keystroke ***REDACTED*** -e "tell app \"System Events\" to keystroke return"'
lock_mac: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'osascript -e "tell application \"System Events\" to keystroke \"q\" using {control down, command down}" 2>/dev/null'

  # MB PRO SERVER
lock_mbpro: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'osascript -e "tell application \"System Events\" to keystroke \"q\" using {control down, command down}" 2>/dev/null'
sleep_mbpro: ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no ***REDACTED*** 'osascript -e "tell app \"System Events\" to sleep" 2>/dev/null'

  ########################################
  #   INTEGRATIONS SECRETS               #
  ########################################

  ## Home Connect Alt ##
homeconnect_id: '***REDACTED***'
homeconnect_secret: '***REDACTED***'

  # ESP DEVICES
wifi_esp: '***REDACTED***'
wifi_password: '***REDACTED***'

  ##Robot Vacuum ##
xiaomi_username: '***REDACTED***'
xiaomi_password: '***REDACTED***'

vacuum_host: '***REDACTED***'
vacuum_token: '***REDACTED***'
vacuum_username: '***REDACTED***'
vacuum_password: '***REDACTED***'

roidmi_host: '***REDACTED***'
roidmi_token: '***REDACTED***'
roidmi_did: '***REDACTED***'

  # TRACKING
tracking_username: '***REDACTED***'
tracking_password: '***REDACTED***'

  # Spotcast ##
sp_dc: '***REDACTED***'
sp_key: '***REDACTED***'

  # ICLOUD
icloud_username: '***REDACTED***'
icloud_password: '***REDACTED***'

  # PLEX
plex_token: '***REDACTED***'
plex_host: '***REDACTED***'

  # ACCUWEATHER
accuweather_api: '***REDACTED***'
accuweather_api_hourly: '***REDACTED***'

waqi_api: '***REDACTED***'

github_token: '***REDACTED***'

homebridge_url: '***REDACTED***'
