#################################################
#                                               #
#         COVERs                                #
#                                               #
#################################################
- entities:
    - cover.living_room_terrace
    - cover.bedroom_shutters
    - cover.door
    - cover.window
  tap_action: false
  double_tap_action: more-info
  state_action:
    action: call-service
    service: floorplan.class_set
    service_data: 'cover-${entity.state}'

- entities:
    - cover.living_room_terrace
  hold_action:
    action: call-service
    service: honeycomb
    service_data:
      autoclose: false
      audio: /local/sound/popup.m4a
      buttons:
        #0 OPEN BASE
        - icon: mdi:arrow-up-drop-circle
          active: '[[[ return entity.attributes.current_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: entity
          #1 TILT OPEN BASE
        - icon: mdi:arrow-top-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 100
          #2 VARIABLE
        - show: false
          #3 TILT CLOSE BASE
        - icon: mdi:arrow-bottom-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 0
          #4 CLOSE BASE
        - icon: mdi:arrow-down-drop-circle
          active: '[[[ return entity.attributes.current_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: entity
          #5 VARIABLE
        - show: false
- entities:
    - cover.bedroom_shutters
  hold_action:
    action: call-service
    service: honeycomb
    service_data:
      autoclose: false
      audio: /local/sound/popup.m4a
      buttons:
        #0 OPEN BASE
        - icon: mdi:arrow-up-drop-circle
          active: '[[[ return entity.attributes.current_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: entity
          #1 TILT OPEN BASE
        - icon: mdi:arrow-top-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 100
          #2 VARIABLE
        - show: false
          #3 TILT CLOSE BASE
        - icon: mdi:arrow-bottom-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 0
          #4 CLOSE BASE
        - icon: mdi:arrow-down-drop-circle
          active: '[[[ return entity.attributes.current_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: entity
          #5 VARIABLE
        - show: false
- entities:
    - cover.door
  hold_action:
    action: call-service
    service: honeycomb
    service_data:
      autoclose: false
      audio: /local/sound/popup.m4a
      buttons:
        #0 OPEN BASE
        - icon: mdi:arrow-up-drop-circle
          active: '[[[ return entity.attributes.current_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: entity
          #1 TILT OPEN BASE
        - icon: mdi:arrow-top-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 100
          #2 VARIABLE
        - show: false
          #3 TILT CLOSE BASE
        - icon: mdi:arrow-bottom-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 0
          #4 CLOSE BASE
        - icon: mdi:arrow-down-drop-circle
          active: '[[[ return entity.attributes.current_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: entity
          #5 VARIABLE
        - show: false
- entities:
    - cover.window
  hold_action:
    action: call-service
    service: honeycomb
    service_data:
      autoclose: false
      audio: /local/sound/popup.m4a
      buttons:
        #0 OPEN BASE
        - icon: mdi:arrow-up-drop-circle
          active: '[[[ return entity.attributes.current_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: entity
          #1 TILT OPEN BASE
        - icon: mdi:arrow-top-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 0 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 100
          #2 VARIABLE
        - show: false
          #3 TILT CLOSE BASE
        - icon: mdi:arrow-bottom-right-bold-box
          active: '[[[ return entity.attributes.current_tilt_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.set_cover_tilt_position
            service_data:
              entity_id: entity
              tilt_position: 0
          #4 CLOSE BASE
        - icon: mdi:arrow-down-drop-circle
          active: '[[[ return entity.attributes.current_position == 100 ]]]'
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: entity
          #5 VARIABLE
        - show: false
